# Generated by Django 6.0.4 on 2026-09-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0007_switch_surrogate_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catmedico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
