# Generated by Django 6.0.4 on 2026-09-22 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_insumos', '0002_medico_fk_integrity'),
        ('catalogos', '0027_catclasificacioncirugia_catdestinoambulancia_and_more'),
        # Dependencia explicita (no solo transitiva via 0024) para forzar el
        # orden de migracion del design: consulta_medica 0025 SIEMPRE antes
        # que almacen_insumos 0003 -- ver sdd/dispensacion-farmacia/design
        # seccion "Migration / Rollout".
        ('consulta_medica', '0025_prescription_item_dispensation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumoconsultadetalle',
            name='prescription_item',
            field=models.ForeignKey(blank=True, db_column='id_receta_item', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumo_detalles', to='consulta_medica.visitprescriptionitem'),
        ),
        migrations.CreateModel(
            name='MedicamentoInsumo',
            fields=[
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(blank=True, db_column='fch_modf', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('id_medicamento_insumo', models.BigAutoField(db_column='id_medicamento_insumo', primary_key=True, serialize=False)),
                ('factor_conversion', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('permite_fraccion', models.BooleanField(default=True)),
                ('insumo', models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.PROTECT, related_name='medicamento_mapeos', to='almacen_insumos.catinsumo')),
                ('medicamento', models.ForeignKey(db_column='id_medic', on_delete=django.db.models.deletion.PROTECT, related_name='insumo_mapeos', to='catalogos.medicamentos')),
            ],
            options={
                'verbose_name': 'Mapeo Medicamento-Insumo',
                'verbose_name_plural': 'Mapeos Medicamento-Insumo',
                'db_table': 'almacen_medicamento_insumo',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('medicamento',), name='almacen_medins_one_active_per_medic'), models.CheckConstraint(condition=models.Q(('factor_conversion__gt', 0)), name='almacen_medins_factor_positivo')],
            },
        ),
    ]
