# Generated by Django 6.0.4 on 2026-09-24 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0029_catcentroatencion_legacy_cd_clinica'),
        ('medicos', '0010_add_legacy_cd_medico'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalAdmission',
            fields=[
                ('id', models.BigAutoField(db_column='id_ingreso', primary_key=True, serialize=False)),
                ('legacy_folio', models.CharField(blank=True, db_column='folio_legado', max_length=20, null=True, unique=True)),
                ('hospital_service_folio', models.CharField(blank=True, db_column='folio_servicio', max_length=20, null=True)),
                ('no_exp', models.CharField(db_column='no_exp', max_length=20)),
                ('pk_num', models.IntegerField(db_column='pk_num', default=0)),
                ('reason', models.TextField(db_column='motivo')),
                ('admission_date', models.DateField(db_column='fecha_ingreso')),
                ('admission_time', models.TimeField(blank=True, db_column='hora_ingreso', null=True)),
                ('admitting_doctor_code_legacy', models.CharField(blank=True, db_column='clave_medico_ingreso_legado', max_length=10, null=True)),
                ('registered_at', models.DateTimeField(blank=True, db_column='fch_registro_ingreso', null=True)),
                ('registered_by_code_legacy', models.CharField(blank=True, db_column='clave_usuario_ingreso_legado', max_length=20, null=True)),
                ('clinical_note_code_legacy', models.CharField(blank=True, db_column='folio_nota_legado', max_length=20, null=True)),
                ('discharge_date', models.DateField(blank=True, db_column='fecha_alta', null=True)),
                ('discharge_time', models.TimeField(blank=True, db_column='hora_alta', null=True)),
                ('discharge_doctor_code_legacy', models.CharField(blank=True, db_column='clave_medico_alta_legado', max_length=10, null=True)),
                ('is_scheduled', models.BooleanField(db_column='es_programado', default=False)),
                ('origin_center_code_legacy', models.IntegerField(blank=True, db_column='clave_clinica_origen_legado', null=True)),
                ('external_folio', models.CharField(blank=True, db_column='folio_externo', max_length=20, null=True)),
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fch_modf')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('admission_type', models.ForeignKey(blank=True, db_column='id_tipo_hospitalizacion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.cattipohospitalizacion')),
                ('admitting_doctor', models.ForeignKey(blank=True, db_column='id_medico_ingreso', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medicos.catmedico')),
                ('discharge_doctor', models.ForeignKey(blank=True, db_column='id_medico_alta', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medicos.catmedico')),
                ('discharge_type', models.ForeignKey(blank=True, db_column='id_tipo_alta', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.cattipoalta')),
                ('origin_center', models.ForeignKey(blank=True, db_column='id_centro_origen', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.catcentroatencion')),
            ],
            options={
                'db_table': 'hsp_admission',
                'ordering': ['-admission_date'],
            },
        ),
        migrations.CreateModel(
            name='HospitalAdmissionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_reason', models.TextField(blank=True, db_column='motivo_anterior', null=True)),
                ('previous_admission_date', models.DateField(blank=True, db_column='fecha_ingreso_anterior', null=True)),
                ('previous_admission_time', models.TimeField(blank=True, db_column='hora_ingreso_anterior', null=True)),
                ('previous_discharge_date', models.DateField(blank=True, db_column='fecha_alta_anterior', null=True)),
                ('previous_discharge_time', models.TimeField(blank=True, db_column='hora_alta_anterior', null=True)),
                ('previous_is_scheduled', models.BooleanField(blank=True, db_column='es_programado_anterior', null=True)),
                ('previous_external_folio', models.CharField(blank=True, db_column='folio_externo_anterior', max_length=20, null=True)),
                ('previous_is_active', models.BooleanField(blank=True, db_column='est_activo_anterior', null=True)),
                ('change_reason', models.TextField(blank=True, db_column='motivo_cambio', null=True)),
                ('changed_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_column='fch_modf')),
                ('admission', models.ForeignKey(db_column='id_ingreso', on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='hospitalizacion.hospitaladmission')),
                ('previous_admission_type', models.ForeignKey(blank=True, db_column='id_tipo_hospitalizacion_anterior', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.cattipohospitalizacion')),
                ('previous_admitting_doctor', models.ForeignKey(blank=True, db_column='id_medico_ingreso_anterior', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medicos.catmedico')),
                ('previous_discharge_doctor', models.ForeignKey(blank=True, db_column='id_medico_alta_anterior', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medicos.catmedico')),
                ('previous_discharge_type', models.ForeignKey(blank=True, db_column='id_tipo_alta_anterior', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.cattipoalta')),
                ('previous_origin_center', models.ForeignKey(blank=True, db_column='id_centro_origen_anterior', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.catcentroatencion')),
            ],
            options={
                'db_table': 'hsp_admission_revision',
                'ordering': ['changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='hospitaladmission',
            index=models.Index(fields=['no_exp', 'pk_num'], name='hsp_admission_no_exp_pk_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitaladmission',
            index=models.Index(fields=['admission_date'], name='hsp_admission_admdate_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitaladmission',
            index=models.Index(fields=['is_active'], name='hsp_admission_active_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitaladmissionrevision',
            index=models.Index(fields=['admission', 'changed_at'], name='hsp_adm_rev_admission_idx'),
        ),
    ]
