# Generated by Django 6.0.4 on 2026-09-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0025_alter_medicamentos_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatCie9Mc',
            fields=[
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(blank=True, db_column='fch_modf', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('id', models.BigAutoField(db_column='id_cie9_mc', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='clave_cie9_mc', max_length=10)),
                ('name', models.CharField(db_column='descripcion_cie9_mc', max_length=400)),
            ],
            options={
                'db_table': 'cat_cie9_mc',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('code',), name='cat_cie9_mc_codigo_uniq')],
            },
        ),
    ]
