# Generated by Django 6.0.4 on 2026-09-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0026_catcie9mc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatClasificacionCirugia',
            fields=[
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(blank=True, db_column='fch_modf', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('id', models.BigAutoField(db_column='id_clasificacion_cirugia', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nombre', max_length=200)),
            ],
            options={
                'db_table': 'cat_clasificacion_cirugia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CatDestinoAmbulancia',
            fields=[
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(blank=True, db_column='fch_modf', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('id', models.BigAutoField(db_column='id_destino_ambulancia', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nombre', max_length=200)),
                ('street', models.CharField(blank=True, db_column='calle', max_length=200, null=True)),
                ('zip_code', models.CharField(blank=True, db_column='codigo_postal', max_length=10, null=True)),
                ('neighborhood', models.CharField(blank=True, db_column='colonia', max_length=150, null=True)),
                ('borough', models.CharField(blank=True, db_column='delegacion', max_length=150, null=True)),
                ('phone', models.CharField(blank=True, db_column='telefono', max_length=40, null=True)),
                ('reference', models.TextField(blank=True, db_column='referencia', null=True)),
            ],
            options={
                'db_table': 'cat_destino_ambulancia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CatMotivoCancelacionCirugia',
            fields=[
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(blank=True, db_column='fch_modf', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('id', models.BigAutoField(db_column='id_motivo_cancelacion_cirugia', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nombre', max_length=200)),
            ],
            options={
                'db_table': 'cat_motivo_cancelacion_cirugia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CatMotivoTraslado',
            fields=[
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(blank=True, db_column='fch_modf', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('id', models.BigAutoField(db_column='id_motivo_traslado', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nombre', max_length=200)),
                ('requires_notes', models.BooleanField(db_column='requiere_notas', default=False, help_text="Si es verdadero, la solicitud exige texto libre en reason_notes (equivalente al motivo 'Otro' del legado).")),
            ],
            options={
                'db_table': 'cat_motivo_traslado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CatTipoCirugia',
            fields=[
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(blank=True, db_column='fch_modf', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('id', models.BigAutoField(db_column='id_tipo_cirugia', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nombre', max_length=200)),
            ],
            options={
                'db_table': 'cat_tipo_cirugia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CatTipoServicioAmbulancia',
            fields=[
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(blank=True, db_column='fch_modf', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('id', models.BigAutoField(db_column='id_tipo_servicio_ambulancia', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nombre', max_length=200)),
            ],
            options={
                'db_table': 'cat_tipo_servicio_ambulancia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CatTipoTraslado',
            fields=[
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(blank=True, db_column='fch_modf', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('id', models.BigAutoField(db_column='id_tipo_traslado', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nombre', max_length=200)),
            ],
            options={
                'db_table': 'cat_tipo_traslado',
                'managed': True,
            },
        ),
    ]
