# Generated by Django 6.0.4 -- catalogos nuevos para hospitalizacion NOM-024
# (change his-hospital-modelo-nom024): reemplazan cat_tphospi/cat_tpaltas
# del legado.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0027_catclasificacioncirugia_catdestinoambulancia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatTipoHospitalizacion',
            fields=[
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(blank=True, db_column='fch_modf', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('id', models.BigAutoField(db_column='id_tipo_hospitalizacion', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nombre', max_length=200)),
                ('legacy_code', models.IntegerField(blank=True, db_column='cd_legado', null=True, unique=True)),
            ],
            options={
                'db_table': 'cat_tipo_hospitalizacion',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CatTipoAlta',
            fields=[
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(blank=True, db_column='fch_modf', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('id', models.BigAutoField(db_column='id_tipo_alta', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nombre', max_length=200)),
                ('legacy_code', models.IntegerField(blank=True, db_column='cd_legado', null=True, unique=True)),
            ],
            options={
                'db_table': 'cat_tipo_alta',
                'ordering': ['name'],
                'managed': True,
            },
        ),
    ]
