# Generated by Django 6.0.4 on 2026-09-28 01:08

from django.db import migrations, models

# Rangos iniciales -- change `diagnosticos-sensibles`. Codigos de CATEGORIA
# de 3 caracteres (sin punto decimal, ver docstring de SensitiveCieRange).
# F10-F19 (sustancias) queda excluido del bloque general de salud mental
# F00-F99, tal como distingue el documento fuente de este change.
#
# IMPORTANTE: estos rangos son un valor por defecto razonable, NO una
# decision final -- deben confirmarse con el area de calidad/juridico del
# hospital antes de considerarse definitivos (ver plan del change).
SEED_RANGOS_SENSIBLES = [
    ("B20", "B24", "hiv", "clinico:diagnosticos_vih:read"),
    ("F10", "F19", "substance_use", "clinico:diagnosticos_sustancias:read"),
    ("F00", "F09", "mental_health", "clinico:diagnosticos_salud_mental:read"),
    ("F20", "F99", "mental_health", "clinico:diagnosticos_salud_mental:read"),
]


def cargar_rangos_semilla(apps, schema_editor):
    SensitiveCieRange = apps.get_model("catalogos", "SensitiveCieRange")
    for start, end, category, permission in SEED_RANGOS_SENSIBLES:
        SensitiveCieRange.objects.get_or_create(
            code_prefix_start=start,
            code_prefix_end=end,
            defaults={"category": category, "required_permission": permission},
        )


def revertir_noop(apps, schema_editor):
    # No borramos las filas semilla al revertir -- mismo criterio que
    # 0021_motivos_cita.py (preferimos no perder el catalogo en un rollback
    # accidental; borrar la tabla en si ya las elimina si hace falta).
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0029_catcentroatencion_legacy_cd_clinica'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensitiveCieRange',
            fields=[
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(blank=True, db_column='fch_modf', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('id', models.BigAutoField(db_column='id_rango_sensible', primary_key=True, serialize=False)),
                ('code_prefix_start', models.CharField(db_column='codigo_inicio', max_length=8)),
                ('code_prefix_end', models.CharField(db_column='codigo_fin', max_length=8)),
                ('category', models.CharField(choices=[('hiv', 'VIH'), ('mental_health', 'Salud mental'), ('substance_use', 'Consumo de sustancias')], db_column='categoria', max_length=20)),
                ('required_permission', models.CharField(db_column='permiso_requerido', max_length=100)),
            ],
            options={
                'db_table': 'cat_rango_cie_sensible',
                'ordering': ['code_prefix_start'],
                'managed': True,
            },
        ),
        migrations.RunPython(cargar_rangos_semilla, revertir_noop),
    ]
