# Generated by Django 6.0.4 on 2026-09-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0030_sensitivecierange'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatEstadoPieza',
            fields=[
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(blank=True, db_column='fch_modf', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('id', models.BigAutoField(db_column='id_estado_pieza', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='clave', max_length=32, unique=True)),
                ('name', models.CharField(db_column='nombre', max_length=100)),
                ('dmft_component', models.CharField(blank=True, choices=[('C', 'Cariado'), ('P', 'Perdido'), ('O', 'Obturado')], db_column='componente_cpod', max_length=1, null=True)),
            ],
            options={
                'db_table': 'cat_estado_pieza',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CatHabito',
            fields=[
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(blank=True, db_column='fch_modf', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('id', models.BigAutoField(db_column='id_habito', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='clave', max_length=40, unique=True)),
                ('name', models.CharField(db_column='nombre', max_length=100)),
            ],
            options={
                'db_table': 'cat_habito',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CatPiezaDental',
            fields=[
                ('fdi', models.CharField(db_column='pieza_fdi', max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nombre', max_length=100)),
                ('dentition', models.CharField(choices=[('P', 'Permanente'), ('T', 'Temporal')], db_column='tp_denticion', max_length=1)),
                ('quadrant', models.PositiveSmallIntegerField(db_column='cuadrante')),
            ],
            options={
                'db_table': 'cat_pieza_dental',
                'ordering': ['fdi'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CatRegionCorporal',
            fields=[
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(blank=True, db_column='fch_modf', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('id', models.BigAutoField(db_column='id_region', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='clave', max_length=40, unique=True)),
                ('name', models.CharField(db_column='nombre', max_length=100)),
                ('order', models.PositiveSmallIntegerField(db_column='orden', default=0)),
            ],
            options={
                'db_table': 'cat_region_corporal',
                'ordering': ['order', 'name'],
                'managed': True,
            },
        ),
    ]
