# Generated by Django 6.0.4 on 2026-09-28 23:49

from django.db import migrations, models

# Codigos EXACTOS del documento "Historia Clinica Unificada" (tabla alergia):
# 1 medicamento, 2 anestesia, 3 material dental, 4 ambiental, 5 alimento, 9 otro.
TIPOS_ALERGIA = (
    (1, "medication", "Medicamento"),
    (2, "anesthesia", "Anestesia"),
    (3, "dental_material", "Material dental"),
    (4, "environmental", "Ambiental"),
    (5, "food", "Alimento"),
    (9, "other", "Otro"),
)


def seed(apps, schema_editor):
    CatTipoAlergia = apps.get_model("catalogos", "CatTipoAlergia")
    for pk, code, name in TIPOS_ALERGIA:
        CatTipoAlergia.objects.update_or_create(id=pk, defaults={"code": code, "name": name})


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0032_seed_catalogos_historia_clinica'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatTipoAlergia',
            fields=[
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(blank=True, db_column='fch_modf', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('id', models.PositiveSmallIntegerField(db_column='cd_tipo_alergia', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='clave', max_length=40, unique=True)),
                ('name', models.CharField(db_column='nombre', max_length=100)),
            ],
            options={
                'db_table': 'cat_tipo_alergia',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.RunPython(seed, migrations.RunPython.noop),
    ]
