# Generated by Django 6.0.4 on 2026-09-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0033_cat_tipo_alergia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensitivecierange',
            name='level',
            field=models.CharField(choices=[('R', 'Restringido'), ('C', 'Confidencial')], db_column='nivel', default='R', max_length=1),
        ),
    ]
