# Generated by Django 6.0.4 on 2026-09-29 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0034_cat_dato_sensible_nivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensitiveAccessProfile',
            fields=[
                ('id', models.BigAutoField(db_column='id_perfil_acceso', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('role', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalogos.roles')),
                ('sensitive_range', models.ForeignKey(db_column='id_rango_sensible', on_delete=django.db.models.deletion.CASCADE, related_name='access_profiles', to='catalogos.sensitivecierange')),
            ],
            options={
                'db_table': 'cat_perfil_acceso_sensible',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('sensitive_range', 'role'), name='cat_perfil_acceso_uniq')],
            },
        ),
    ]
