# Generated by Django 6.0.4 on 2026-09-14 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0027_catclasificacioncirugia_catdestinoambulancia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceRequest',
            fields=[
                ('id', models.BigAutoField(db_column='id_solicitud', primary_key=True, serialize=False)),
                ('folio', models.CharField(db_column='folio', max_length=32, unique=True)),
                ('legacy_folio', models.CharField(blank=True, db_column='folio_legado', max_length=20, null=True)),
                ('no_exp', models.CharField(db_column='no_exp', db_index=True, max_length=20)),
                ('pk_num', models.IntegerField(db_column='pk_num', default=0)),
                ('requesting_clinic_id', models.CharField(db_column='cd_clinica', max_length=10)),
                ('requested_by_name', models.CharField(db_column='nombre_solicita', max_length=200)),
                ('social_work_notes', models.TextField(blank=True, db_column='notas_trabajo_social', null=True)),
                ('reason_notes', models.TextField(blank=True, db_column='notas_motivo', null=True)),
                ('diagnosis_text', models.TextField(blank=True, db_column='diagnostico', null=True)),
                ('origin_street', models.CharField(blank=True, db_column='calle_origen', max_length=200, null=True)),
                ('origin_zip', models.CharField(blank=True, db_column='cp_origen', max_length=10, null=True)),
                ('origin_neighborhood', models.CharField(blank=True, db_column='colonia_origen', max_length=150, null=True)),
                ('origin_borough', models.CharField(blank=True, db_column='delegacion_origen', max_length=150, null=True)),
                ('origin_phone', models.CharField(blank=True, db_column='telefono_origen', max_length=40, null=True)),
                ('origin_reference', models.TextField(blank=True, db_column='referencia_origen', null=True)),
                ('status', models.CharField(choices=[('activa', 'Activa'), ('baja', 'Baja')], db_column='estatus', default='activa', max_length=20)),
                ('authorization_status', models.CharField(choices=[('pendiente', 'Pendiente'), ('autorizada', 'Autorizada'), ('rechazada', 'Rechazada')], db_column='estatus_autorizacion', default='pendiente', max_length=20)),
                ('authorized_by_id', models.BigIntegerField(blank=True, db_column='autorizado_por', null=True)),
                ('authorized_at', models.DateTimeField(blank=True, db_column='fecha_autorizacion', null=True)),
                ('service_number', models.CharField(blank=True, db_column='no_servicio', max_length=30, null=True)),
                ('rejection_notes', models.TextField(blank=True, db_column='notas_rechazo', null=True)),
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fch_modf')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('destination', models.ForeignKey(db_column='id_destino', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.catdestinoambulancia')),
                ('reason', models.ForeignKey(db_column='id_motivo', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.catmotivotraslado')),
                ('requested_by_relationship', models.ForeignKey(blank=True, db_column='id_parentesco', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.parentesco')),
            ],
            options={
                'db_table': 'amb_request',
            },
        ),
        migrations.CreateModel(
            name='AmbulanceRequestSchedule',
            fields=[
                ('id', models.BigAutoField(db_column='id_solicitud_fecha', primary_key=True, serialize=False)),
                ('transfer_date', models.DateField(db_column='fecha_traslado')),
                ('transfer_time', models.TimeField(db_column='hora_traslado')),
                ('status', models.CharField(choices=[('activa', 'Activa'), ('baja', 'Baja')], db_column='estatus', default='activa', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('request', models.ForeignKey(db_column='id_solicitud', on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='ambulancias.ambulancerequest')),
                ('service_type', models.ForeignKey(db_column='id_tipo_servicio', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.cattiposervicioambulancia')),
                ('transfer_type', models.ForeignKey(db_column='id_tipo_traslado', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.cattipotraslado')),
            ],
            options={
                'db_table': 'amb_request_schedule',
            },
        ),
        migrations.AddIndex(
            model_name='ambulancerequest',
            index=models.Index(fields=['no_exp', 'pk_num'], name='amb_request_patient_idx'),
        ),
        migrations.AddIndex(
            model_name='ambulancerequest',
            index=models.Index(fields=['authorization_status'], name='amb_request_authstatus_idx'),
        ),
        migrations.AddIndex(
            model_name='ambulancerequestschedule',
            index=models.Index(fields=['request'], name='amb_reqsched_request_idx'),
        ),
    ]
