# Generated by Django 6.0.4 on 2026-09-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_medica', '0017_visitconsultation_soap_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalhistory',
            name='phone',
            field=models.CharField(blank=True, db_column='telefono', max_length=50, null=True),
        ),
    ]
