# Generated by Django 6.0.4 on 2026-09-14 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0027_catclasificacioncirugia_catdestinoambulancia_and_more'),
        ('consulta_medica', '0018_clinicalhistory_phone_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalHistoryRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_phone', models.CharField(blank=True, db_column='telefono_anterior', max_length=50, null=True)),
                ('previous_family_history', models.TextField(blank=True, db_column='antecedentes_anterior', null=True)),
                ('previous_current_illness', models.TextField(blank=True, db_column='padecimiento_actual_anterior', null=True)),
                ('previous_systems_review', models.TextField(blank=True, db_column='organos_aparatos_sistemas_anterior', null=True)),
                ('previous_head_exam', models.TextField(blank=True, db_column='exploracion_cabeza_anterior', null=True)),
                ('previous_neck_exam', models.TextField(blank=True, db_column='exploracion_cuello_anterior', null=True)),
                ('previous_chest_exam', models.TextField(blank=True, db_column='exploracion_torax_anterior', null=True)),
                ('previous_abdomen_exam', models.TextField(blank=True, db_column='exploracion_abdomen_anterior', null=True)),
                ('previous_genitals_exam', models.TextField(blank=True, db_column='exploracion_genitales_anterior', null=True)),
                ('previous_limbs_exam', models.TextField(blank=True, db_column='exploracion_miembros_anterior', null=True)),
                ('previous_diagnostic_management', models.TextField(blank=True, db_column='manejo_diagnostico_anterior', null=True)),
                ('previous_therapeutic_management', models.TextField(blank=True, db_column='manejo_terapeutico_anterior', null=True)),
                ('previous_allergies', models.TextField(blank=True, db_column='alergias_anterior', null=True)),
                ('changed_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_column='fch_modf')),
                ('history', models.ForeignKey(db_column='id_historia', on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='consulta_medica.clinicalhistory')),
                ('previous_education_level', models.ForeignKey(blank=True, db_column='id_escolaridad_anterior', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.escolaridad')),
                ('previous_marital_status', models.ForeignKey(blank=True, db_column='id_edocivil_anterior', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.edocivil')),
                ('previous_occupation', models.ForeignKey(blank=True, db_column='id_ocupacion_anterior', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.ocupaciones')),
                ('previous_religion', models.ForeignKey(blank=True, db_column='id_religion_anterior', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.religion')),
                ('previous_residence_type', models.ForeignKey(blank=True, db_column='id_residencia_anterior', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.tiporesidencia')),
            ],
            options={
                'db_table': 'cns_clinical_history_revision',
                'ordering': ['changed_at'],
            },
        ),
    ]
