# Generated by Django 6.0.4 on 2026-09-14 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_medica', '0019_clinicalhistory_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationAddendum',
            fields=[
                ('id_addendum', models.BigAutoField(db_column='id_adenda', primary_key=True, serialize=False)),
                ('text', models.TextField(db_column='texto')),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('consultation', models.ForeignKey(db_column='id_consulta', on_delete=django.db.models.deletion.PROTECT, related_name='addenda', to='consulta_medica.visitconsultation')),
            ],
            options={
                'db_table': 'cns_consultation_addendum',
                'ordering': ['created_at'],
            },
        ),
    ]
