# Generated by Django 6.0.4 on 2026-09-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_medica', '0020_consultation_addendum'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyConsultationRecord',
            fields=[
                ('id_legacy_record', models.BigAutoField(db_column='id_registro', primary_key=True, serialize=False)),
                ('legacy_folio', models.CharField(db_column='folio_legado', max_length=20, unique=True)),
                ('no_exp', models.CharField(db_column='no_exp', db_index=True, max_length=20)),
                ('pk_num', models.IntegerField(db_column='pk_num', default=0)),
                ('consultation_date', models.DateField(db_column='fecha_consulta')),
                ('consultation_time', models.CharField(blank=True, db_column='hora_consulta', max_length=10, null=True)),
                ('doctor_code_legacy', models.CharField(blank=True, db_column='clave_medico_legado', max_length=10, null=True)),
                ('clinic_code_legacy', models.IntegerField(blank=True, db_column='clave_clinica_legado', null=True)),
                ('subjective', models.TextField(blank=True, db_column='subjetivo', null=True)),
                ('objective', models.TextField(blank=True, db_column='objetivo', null=True)),
                ('assessment', models.TextField(blank=True, db_column='analisis', null=True)),
                ('plan', models.TextField(blank=True, db_column='plan', null=True)),
                ('diagnostic_impression', models.TextField(blank=True, db_column='impresion_diagnostica', null=True)),
                ('primary_cie_code_legacy', models.IntegerField(blank=True, db_column='clave_cie_principal_legado', null=True)),
                ('addendum_legacy', models.TextField(blank=True, db_column='adenda_legado', null=True)),
                ('weight_legacy', models.CharField(blank=True, db_column='peso_legado', max_length=8, null=True)),
                ('height_legacy', models.CharField(blank=True, db_column='talla_legado', max_length=8, null=True)),
                ('blood_pressure_legacy', models.CharField(blank=True, db_column='ta_legado', max_length=7, null=True)),
                ('pulse_legacy', models.CharField(blank=True, db_column='pulso_legado', max_length=20, null=True)),
                ('temperature_legacy', models.CharField(blank=True, db_column='temperatura_legado', max_length=10, null=True)),
                ('respiration_legacy', models.CharField(blank=True, db_column='respiracion_legado', max_length=20, null=True)),
                ('bmi_legacy', models.CharField(blank=True, db_column='imc_legado', max_length=8, null=True)),
                ('glucose_legacy', models.CharField(blank=True, db_column='glucosa_legado', max_length=10, null=True)),
                ('is_first_visit_legacy', models.BooleanField(blank=True, db_column='es_primera_vez_legado', null=True)),
                ('status_legacy', models.CharField(blank=True, db_column='estatus_legado', max_length=1, null=True)),
                ('migrated_at', models.DateTimeField(auto_now_add=True, db_column='fch_migracion')),
            ],
            options={
                'db_table': 'cns_legacy_consultation_record',
                'ordering': ['-consultation_date'],
                'indexes': [models.Index(fields=['no_exp', 'pk_num'], name='cns_legacy_cons_noexp_pk_idx'), models.Index(fields=['consultation_date'], name='cns_legacy_cons_date_idx')],
            },
        ),
    ]
