# Generated by Django 6.0.4 on 2026-09-14 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_medica', '0021_legacy_consultation_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyConsultationDiagnosis',
            fields=[
                ('id_legacy_diagnosis', models.BigAutoField(db_column='id_diagnostico_legado', primary_key=True, serialize=False)),
                ('legacy_id', models.BigIntegerField(db_column='id_legado', unique=True)),
                ('legacy_folio', models.CharField(db_column='folio_legado', db_index=True, max_length=20)),
                ('cie_code_legacy', models.IntegerField(db_column='clave_cie_legado')),
                ('doctor_code_legacy', models.CharField(blank=True, db_column='clave_medico_legado', max_length=10, null=True)),
                ('clinic_code_legacy', models.IntegerField(blank=True, db_column='clave_clinica_legado', null=True)),
                ('status_legacy', models.CharField(blank=True, db_column='estatus_legado', max_length=2, null=True)),
                ('migrated_at', models.DateTimeField(auto_now_add=True, db_column='fch_migracion')),
                ('record', models.ForeignKey(blank=True, db_column='id_registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_diagnoses', to='consulta_medica.legacyconsultationrecord')),
            ],
            options={
                'db_table': 'cns_legacy_consultation_diagnosis',
                'indexes': [models.Index(fields=['legacy_folio'], name='cns_legacy_diag_folio_idx'), models.Index(fields=['cie_code_legacy'], name='cns_legacy_diag_cie_idx')],
            },
        ),
    ]
