# Generated by Django 6.0.4 on 2026-09-14 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_medica', '0022_legacy_consultation_diagnosis'),
        ('recepcion', '0024_motivo_cancelacion_catalogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionAuthorization',
            fields=[
                ('id_authorization', models.BigAutoField(db_column='id_autorizacion', primary_key=True, serialize=False)),
                ('medications_count', models.PositiveIntegerField(db_column='no_medicamentos', default=0)),
                ('specialized_count', models.PositiveIntegerField(db_column='no_especializado', default=0)),
                ('controlled_count', models.PositiveIntegerField(db_column='no_controlado', default=0)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('autorizada', 'Autorizada'), ('rechazada', 'Rechazada')], db_column='estatus', default='pendiente', max_length=20)),
                ('authorized_by_id', models.BigIntegerField(blank=True, db_column='usr_autoriza', null=True)),
                ('authorized_at', models.DateTimeField(blank=True, db_column='fch_autoriza', null=True)),
                ('rejection_reason', models.CharField(blank=True, db_column='motivo_rechazo', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fch_modf')),
                ('prescription', models.ForeignKey(db_column='id_receta', on_delete=django.db.models.deletion.PROTECT, related_name='authorizations', to='consulta_medica.visitprescription')),
                ('visit', models.ForeignKey(db_column='id_visit', on_delete=django.db.models.deletion.PROTECT, related_name='prescription_authorizations', to='recepcion.visit')),
            ],
            options={
                'db_table': 'cns_prescription_authorization',
                'indexes': [models.Index(fields=['status'], name='cns_rxauth_status_idx'), models.Index(fields=['prescription'], name='cns_rxauth_prescription_idx')],
            },
        ),
    ]
