# Generated by Django 6.0.4 on 2026-09-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_medica', '0023_prescription_authorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionauthorization',
            name='prescribed_by_id',
            field=models.BigIntegerField(blank=True, db_column='usr_prescribe', null=True),
        ),
    ]
