# Generated by Django 6.0.4 on 2026-09-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0027_catclasificacioncirugia_catdestinoambulancia_and_more'),
        ('consulta_medica', '0024_prescription_authorization_segregation'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitprescriptionitem',
            name='dispensation_status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('dispensado', 'Dispensado')], db_column='estatus_dispensacion', default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='visitprescriptionitem',
            name='dispensed_quantity',
            field=models.PositiveIntegerField(db_column='cantidad_dispensada', default=0),
        ),
        migrations.AddConstraint(
            model_name='visitprescriptionitem',
            constraint=models.CheckConstraint(condition=models.Q(('dispensed_quantity__lte', models.F('quantity'))), name='cns_rxitem_dispensed_lte_quantity'),
        ),
    ]
