# Generated by Django 6.0.4 on 2026-09-28 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0029_catcentroatencion_legacy_cd_clinica'),
        ('consulta_medica', '0025_prescription_item_dispensation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id_allergy', models.BigAutoField(db_column='id_alergia', primary_key=True, serialize=False)),
                ('no_exp', models.CharField(db_column='no_exp', db_index=True, max_length=20)),
                ('pk_num', models.IntegerField(db_column='pk_num', default=0)),
                ('category', models.CharField(choices=[('medication', 'Medicamento'), ('dental_material', 'Material dental'), ('anesthesia', 'Anestesia'), ('food', 'Alimento'), ('environmental', 'Ambiental'), ('other', 'Otro')], db_column='categoria', max_length=20)),
                ('substance', models.CharField(db_column='sustancia', max_length=255)),
                ('severity', models.CharField(choices=[('mild', 'Leve'), ('moderate', 'Moderada'), ('severe', 'Grave')], db_column='severidad', max_length=20)),
                ('reaction', models.TextField(blank=True, db_column='reaccion', null=True)),
                ('source', models.CharField(choices=[('general', 'Medicina General'), ('stomatology', 'Estomatologia')], db_column='origen', max_length=20)),
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fch_modf')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('medication', models.ForeignKey(blank=True, db_column='id_medic', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.medicamentos')),
            ],
            options={
                'db_table': 'cns_allergy',
            },
        ),
        migrations.CreateModel(
            name='AllergyRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_category', models.CharField(choices=[('medication', 'Medicamento'), ('dental_material', 'Material dental'), ('anesthesia', 'Anestesia'), ('food', 'Alimento'), ('environmental', 'Ambiental'), ('other', 'Otro')], db_column='categoria_anterior', max_length=20)),
                ('previous_substance', models.CharField(db_column='sustancia_anterior', max_length=255)),
                ('previous_severity', models.CharField(choices=[('mild', 'Leve'), ('moderate', 'Moderada'), ('severe', 'Grave')], db_column='severidad_anterior', max_length=20)),
                ('previous_reaction', models.TextField(blank=True, db_column='reaccion_anterior', null=True)),
                ('changed_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_column='fch_modf')),
                ('allergy', models.ForeignKey(db_column='id_alergia', on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='consulta_medica.allergy')),
                ('previous_medication', models.ForeignKey(blank=True, db_column='id_medic_anterior', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.medicamentos')),
            ],
            options={
                'db_table': 'cns_allergy_revision',
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='StomatologyHistoryRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_family_diabetes', models.BooleanField(db_column='af_diabetes_anterior')),
                ('previous_family_cancer', models.BooleanField(db_column='af_cancer_anterior')),
                ('previous_family_high_blood_pressure', models.BooleanField(db_column='af_presion_alta_anterior')),
                ('previous_family_low_blood_pressure', models.BooleanField(db_column='af_presion_baja_anterior')),
                ('previous_cause_of_death', models.CharField(blank=True, db_column='causa_muerte_anterior', max_length=255, null=True)),
                ('previous_personal_diabetes', models.BooleanField(db_column='app_diabetes_anterior')),
                ('previous_personal_asthma', models.BooleanField(db_column='app_asma_anterior')),
                ('previous_personal_high_blood_pressure', models.BooleanField(db_column='app_presion_alta_anterior')),
                ('previous_personal_low_blood_pressure', models.BooleanField(db_column='app_presion_baja_anterior')),
                ('previous_personal_hepatitis', models.BooleanField(db_column='app_hepatitis_anterior')),
                ('previous_personal_hiv', models.BooleanField(db_column='app_vih_anterior')),
                ('previous_personal_smoking', models.BooleanField(db_column='app_tabaquismo_anterior')),
                ('previous_personal_alcoholism', models.BooleanField(db_column='app_alcoholismo_anterior')),
                ('previous_personal_substance_abuse', models.BooleanField(db_column='app_toxicomanias_anterior')),
                ('previous_habits', models.TextField(blank=True, db_column='habitos_anterior', null=True)),
                ('previous_diet', models.TextField(blank=True, db_column='alimentacion_anterior', null=True)),
                ('previous_surgical_history', models.TextField(blank=True, db_column='antecedentes_quirurgicos_anterior', null=True)),
                ('previous_traumatic_history', models.TextField(blank=True, db_column='antecedentes_traumaticos_anterior', null=True)),
                ('previous_current_illness_history', models.TextField(blank=True, db_column='padecimiento_actual_anterior', null=True)),
                ('changed_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_column='fch_modf')),
                ('history', models.ForeignKey(db_column='id_historia_dental', on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='consulta_medica.stomatologyhistory')),
            ],
            options={
                'db_table': 'cns_stomatology_history_revision',
                'ordering': ['changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='allergy',
            index=models.Index(fields=['no_exp', 'pk_num'], name='cns_allergy_patient_idx'),
        ),
        migrations.AddIndex(
            model_name='allergy',
            index=models.Index(fields=['is_active'], name='cns_allergy_active_idx'),
        ),
    ]
