# Generated by Django 6.0.4 on 2026-09-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_medica', '0026_allergy_allergyrevision_stomatologyhistoryrevision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalhistory',
            name='curp',
            field=models.CharField(blank=True, db_column='curp', db_index=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='sex',
            field=models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer'), ('X', 'No binario')], db_column='sexo', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='clinicalhistoryrevision',
            name='previous_curp',
            field=models.CharField(blank=True, db_column='curp_anterior', max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='clinicalhistoryrevision',
            name='previous_sex',
            field=models.CharField(blank=True, db_column='sexo_anterior', max_length=1, null=True),
        ),
    ]
