# Generated by Django 6.0.4 on 2026-09-28 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0033_cat_tipo_alergia'),
        ('consulta_medica', '0030_historia_clinica_unificada_limpieza'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergy',
            name='allergy_type',
            field=models.ForeignKey(blank=True, db_column='cd_tipo_alergia', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.cattipoalergia'),
        ),
        migrations.AddField(
            model_name='allergyrevision',
            name='previous_allergy_type',
            field=models.ForeignKey(blank=True, db_column='cd_tipo_alergia_anterior', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.cattipoalergia'),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='opened_on',
            field=models.DateField(blank=True, db_column='fe_apertura', null=True),
        ),
        migrations.AddField(
            model_name='historicalnote',
            name='clinical_history',
            field=models.ForeignKey(blank=True, db_column='id_historia', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historical_notes', to='consulta_medica.clinicalhistory'),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_patient', models.BigAutoField(db_column='id_paciente', primary_key=True, serialize=False)),
                ('no_exp', models.CharField(db_column='no_exp', max_length=20)),
                ('pk_num', models.IntegerField(db_column='tp_paciente', default=0)),
                ('curp', models.CharField(blank=True, db_column='curp', db_index=True, max_length=18, null=True)),
                ('sex', models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer'), ('X', 'No binario')], db_column='sexo', max_length=1, null=True)),
                ('phone', models.CharField(blank=True, db_column='ds_telefono', max_length=50, null=True)),
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fch_modf')),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('education_level', models.ForeignKey(blank=True, db_column='cd_escolaridad', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.escolaridad')),
                ('marital_status', models.ForeignKey(blank=True, db_column='cd_edocivil', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.edocivil')),
                ('occupation', models.ForeignKey(blank=True, db_column='cd_ocupacion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.ocupaciones')),
                ('religion', models.ForeignKey(blank=True, db_column='cd_religion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.religion')),
                ('residence_type', models.ForeignKey(blank=True, db_column='cd_residencia', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.tiporesidencia')),
            ],
            options={
                'db_table': 'cns_paciente',
            },
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='patient',
            field=models.OneToOneField(blank=True, db_column='id_paciente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_history', to='consulta_medica.patient'),
        ),
        migrations.CreateModel(
            name='PatientRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_curp', models.CharField(blank=True, db_column='curp_anterior', max_length=18, null=True)),
                ('previous_sex', models.CharField(blank=True, db_column='sexo_anterior', max_length=1, null=True)),
                ('previous_phone', models.CharField(blank=True, db_column='ds_telefono_anterior', max_length=50, null=True)),
                ('changed_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_column='fch_modf')),
                ('patient', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='consulta_medica.patient')),
                ('previous_education_level', models.ForeignKey(blank=True, db_column='cd_escolaridad_anterior', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.escolaridad')),
                ('previous_marital_status', models.ForeignKey(blank=True, db_column='cd_edocivil_anterior', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.edocivil')),
                ('previous_occupation', models.ForeignKey(blank=True, db_column='cd_ocupacion_anterior', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.ocupaciones')),
                ('previous_religion', models.ForeignKey(blank=True, db_column='cd_religion_anterior', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.religion')),
                ('previous_residence_type', models.ForeignKey(blank=True, db_column='cd_residencia_anterior', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.tiporesidencia')),
            ],
            options={
                'db_table': 'cns_paciente_revision',
                'ordering': ['changed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('no_exp', 'pk_num'), name='cns_paciente_uniq'),
        ),
    ]
