# Generated by Django 6.0.4 on 2026-09-28 23:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0033_cat_tipo_alergia'),
        ('consulta_medica', '0032_paciente_datos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalhistoryrevision',
            name='history',
        ),
        migrations.RemoveField(
            model_name='clinicalhistoryrevision',
            name='previous_education_level',
        ),
        migrations.RemoveField(
            model_name='clinicalhistoryrevision',
            name='previous_marital_status',
        ),
        migrations.RemoveField(
            model_name='clinicalhistoryrevision',
            name='previous_occupation',
        ),
        migrations.RemoveField(
            model_name='clinicalhistoryrevision',
            name='previous_religion',
        ),
        migrations.RemoveField(
            model_name='clinicalhistoryrevision',
            name='previous_residence_type',
        ),
        migrations.RemoveField(
            model_name='allergy',
            name='category',
        ),
        migrations.RemoveField(
            model_name='allergyrevision',
            name='previous_category',
        ),
        migrations.RemoveField(
            model_name='clinicalhistory',
            name='curp',
        ),
        migrations.RemoveField(
            model_name='clinicalhistory',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='clinicalhistory',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='clinicalhistory',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='clinicalhistory',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='clinicalhistory',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='clinicalhistory',
            name='residence_type',
        ),
        migrations.RemoveField(
            model_name='clinicalhistory',
            name='sex',
        ),
        migrations.AlterField(
            model_name='allergy',
            name='allergy_type',
            field=models.ForeignKey(db_column='cd_tipo_alergia', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.cattipoalergia'),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='severity',
            field=models.CharField(choices=[('L', 'Leve'), ('M', 'Moderada'), ('G', 'Grave')], db_column='severidad', max_length=1),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='status',
            field=models.CharField(choices=[('A', 'Activa'), ('R', 'Resuelta'), ('E', 'Capturada por error')], db_column='estado', default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='allergyrevision',
            name='previous_allergy_type',
            field=models.ForeignKey(db_column='cd_tipo_alergia_anterior', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.cattipoalergia'),
        ),
        migrations.AlterField(
            model_name='allergyrevision',
            name='previous_severity',
            field=models.CharField(choices=[('L', 'Leve'), ('M', 'Moderada'), ('G', 'Grave')], db_column='severidad_anterior', max_length=1),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='opened_on',
            field=models.DateField(db_column='fe_apertura', default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='patient',
            field=models.OneToOneField(db_column='id_paciente', on_delete=django.db.models.deletion.PROTECT, related_name='clinical_history', to='consulta_medica.patient'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='status',
            field=models.CharField(choices=[('A', 'Actual'), ('E', 'Ex (ya no lo practica)')], db_column='estado', default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalnote',
            name='clinical_history',
            field=models.ForeignKey(db_column='id_historia', on_delete=django.db.models.deletion.PROTECT, related_name='historical_notes', to='consulta_medica.clinicalhistory'),
        ),
        migrations.AlterField(
            model_name='historicalnote',
            name='origin',
            field=models.CharField(choices=[('M', 'Migrado del sistema anterior'), ('V', 'Version anterior de la historia')], db_column='origen', default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='personalhistory',
            name='status',
            field=models.CharField(choices=[('A', 'Activo'), ('R', 'Resuelto')], db_column='estado', default='A', max_length=1),
        ),
        migrations.AddIndex(
            model_name='allergy',
            index=models.Index(fields=['no_exp', 'pk_num', 'status'], name='ix_alergia_paciente'),
        ),
        migrations.DeleteModel(
            name='ClinicalHistoryRevision',
        ),
    ]
