# Generated by Django 6.0.4 on 2026-09-29 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_medica', '0033_paciente_limpieza'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergy',
            name='service_origin_code',
            field=models.PositiveSmallIntegerField(blank=True, db_column='cd_servicio_origen', null=True),
        ),
        migrations.AddField(
            model_name='odontogram',
            name='dmft_total',
            field=models.DecimalField(blank=True, db_column='indice_cpod', decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='odontogram',
            name='stomatology_history',
            field=models.ForeignKey(blank=True, db_column='id_hc_estoma', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='odontograms', to='consulta_medica.stomatologyhistory'),
        ),
        migrations.AddField(
            model_name='stomatologyhistory',
            name='clinical_history',
            field=models.OneToOneField(blank=True, db_column='id_historia', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stomatology_section', to='consulta_medica.clinicalhistory'),
        ),
    ]
