# Generated by Django 6.0.4 on 2026-09-29 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_medica', '0035_documento_estructura_datos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergy',
            name='source',
        ),
        migrations.AlterField(
            model_name='allergy',
            name='service_origin_code',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Medicina General'), (5, 'Odontologia')], db_column='cd_servicio_origen'),
        ),
        migrations.AlterField(
            model_name='odontogram',
            name='dmft_total',
            field=models.DecimalField(db_column='indice_cpod', decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='odontogram',
            name='stomatology_history',
            field=models.ForeignKey(db_column='id_hc_estoma', on_delete=django.db.models.deletion.PROTECT, related_name='odontograms', to='consulta_medica.stomatologyhistory'),
        ),
        migrations.AlterField(
            model_name='stomatologyhistory',
            name='clinical_history',
            field=models.OneToOneField(db_column='id_historia', on_delete=django.db.models.deletion.PROTECT, related_name='stomatology_section', to='consulta_medica.clinicalhistory'),
        ),
    ]
