# Generated by Django 6.0.4 on 2026-09-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_medica', '0036_documento_estructura_limpieza'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitconsultation',
            name='current_illness',
            field=models.TextField(blank=True, db_column='ds_padecimiento', null=True),
        ),
        migrations.AddField(
            model_name='visitconsultation',
            name='diagnostic_plan',
            field=models.TextField(blank=True, db_column='ds_plan_diagnostico', null=True),
        ),
        migrations.AddField(
            model_name='visitconsultation',
            name='systems_review',
            field=models.TextField(blank=True, db_column='ds_aparatos_sistemas', null=True),
        ),
        migrations.AddField(
            model_name='visitconsultation',
            name='therapeutic_plan',
            field=models.TextField(blank=True, db_column='ds_plan_terapeutico', null=True),
        ),
        migrations.AddField(
            model_name='visitconsultationrevision',
            name='previous_current_illness',
            field=models.TextField(blank=True, db_column='ds_padecimiento_anterior', null=True),
        ),
        migrations.AddField(
            model_name='visitconsultationrevision',
            name='previous_diagnostic_plan',
            field=models.TextField(blank=True, db_column='ds_plan_diagnostico_anterior', null=True),
        ),
        migrations.AddField(
            model_name='visitconsultationrevision',
            name='previous_systems_review',
            field=models.TextField(blank=True, db_column='ds_aparatos_sistemas_anterior', null=True),
        ),
        migrations.AddField(
            model_name='visitconsultationrevision',
            name='previous_therapeutic_plan',
            field=models.TextField(blank=True, db_column='ds_plan_terapeutico_anterior', null=True),
        ),
    ]
