# Generated by Django 6.0.4 on 2026-09-29 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_medica', '0037_nota_consulta_ampliada'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyVitalSigns',
            fields=[
                ('id_legacy_vitals', models.BigAutoField(db_column='id_signos', primary_key=True, serialize=False)),
                ('no_exp', models.CharField(db_column='no_exp', max_length=20)),
                ('pk_num', models.IntegerField(db_column='pk_num', default=0)),
                ('specialty', models.CharField(choices=[('general', 'Medicina General'), ('stomatology', 'Estomatologia'), ('legacy', 'Migrado del sistema anterior')], db_column='especialidad', default='general', max_length=20)),
                ('measured_on', models.DateField(blank=True, db_column='fe_medicion', null=True)),
                ('weight_kg', models.DecimalField(blank=True, db_column='no_peso', decimal_places=2, max_digits=6, null=True)),
                ('height_cm', models.DecimalField(blank=True, db_column='no_talla', decimal_places=2, max_digits=6, null=True)),
                ('blood_pressure_systolic', models.PositiveSmallIntegerField(blank=True, db_column='no_ta_sistolica', null=True)),
                ('blood_pressure_diastolic', models.PositiveSmallIntegerField(blank=True, db_column='no_ta_diastolica', null=True)),
                ('heart_rate_bpm', models.PositiveSmallIntegerField(blank=True, db_column='no_pulso', null=True)),
                ('temperature_c', models.DecimalField(blank=True, db_column='no_temp', decimal_places=1, max_digits=4, null=True)),
                ('respiratory_rate_bpm', models.PositiveSmallIntegerField(blank=True, db_column='no_resp', null=True)),
                ('bmi', models.DecimalField(blank=True, db_column='no_imc', decimal_places=2, max_digits=6, null=True)),
                ('raw_text', models.TextField(db_column='ds_texto_original')),
                ('legacy_ref', models.CharField(db_column='ref_origen', max_length=60, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('clinical_history', models.ForeignKey(db_column='id_historia', on_delete=django.db.models.deletion.PROTECT, related_name='legacy_vital_signs', to='consulta_medica.clinicalhistory')),
            ],
            options={
                'db_table': 'cns_signos_vitales_legado',
                'ordering': ['measured_on', 'id_legacy_vitals'],
                'indexes': [models.Index(fields=['no_exp', 'pk_num'], name='cns_sv_legado_patient_idx')],
            },
        ),
    ]
