# Generated by Django 6.0.4 on 2026-09-29 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_medica', '0039_signos_vitales_legado_datos'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyMigrationRun',
            fields=[
                ('id_run', models.BigAutoField(db_column='id_ejecucion', primary_key=True, serialize=False)),
                ('command', models.CharField(db_column='comando', max_length=80)),
                ('operator', models.CharField(db_column='operador', max_length=100)),
                ('host', models.CharField(blank=True, db_column='equipo', max_length=100, null=True)),
                ('options', models.TextField(blank=True, db_column='opciones', null=True)),
                ('dry_run', models.BooleanField(db_column='sw_simulacion', default=False)),
                ('status', models.CharField(choices=[('E', 'En curso'), ('O', 'Terminada'), ('F', 'Fallida')], db_column='estatus', default='E', max_length=1)),
                ('rows_read', models.IntegerField(blank=True, db_column='filas_leidas', null=True)),
                ('summary', models.TextField(blank=True, db_column='resumen', null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_column='fch_inicio')),
                ('finished_at', models.DateTimeField(blank=True, db_column='fch_fin', null=True)),
            ],
            options={
                'db_table': 'cns_bitacora_migracion',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LegacyMigrationConflict',
            fields=[
                ('id_conflict', models.BigAutoField(db_column='id_conflicto', primary_key=True, serialize=False)),
                ('no_exp', models.CharField(db_column='no_exp', max_length=20)),
                ('pk_num', models.IntegerField(db_column='tp_paciente', default=0)),
                ('field', models.CharField(db_column='campo', max_length=40)),
                ('kept_value', models.CharField(blank=True, db_column='valor_conservado', max_length=255, null=True)),
                ('discarded_value', models.CharField(blank=True, db_column='valor_descartado', max_length=255, null=True)),
                ('legacy_ref', models.CharField(db_column='ref_origen', max_length=60)),
                ('legacy_date', models.DateField(blank=True, db_column='fe_origen', null=True)),
                ('winner', models.CharField(choices=[('L', 'Legado mas reciente (se aplico)'), ('P', 'Se conservo el legado previo (mas reciente o igual)'), ('S', 'Se conservo lo editado en SIRES')], db_column='ganador', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('run', models.ForeignKey(blank=True, db_column='id_ejecucion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conflicts', to='consulta_medica.legacymigrationrun')),
            ],
            options={
                'db_table': 'cns_conflicto_migracion',
                'ordering': ['no_exp', 'pk_num', 'field'],
                'indexes': [models.Index(fields=['no_exp', 'pk_num'], name='cns_conflicto_patient_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatientLegacySource',
            fields=[
                ('id_source', models.BigAutoField(db_column='id_origen', primary_key=True, serialize=False)),
                ('field', models.CharField(db_column='campo', max_length=40)),
                ('value', models.CharField(db_column='valor', max_length=255)),
                ('legacy_ref', models.CharField(db_column='ref_origen', max_length=60)),
                ('legacy_date', models.DateField(blank=True, db_column='fe_origen', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fch_modf')),
                ('patient', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, related_name='legacy_sources', to='consulta_medica.patient')),
            ],
            options={
                'db_table': 'cns_paciente_origen_legado',
                'constraints': [models.UniqueConstraint(fields=('patient', 'field'), name='cns_paciente_origen_campo_uq')],
            },
        ),
    ]
