# Generated by Django 6.0.4 on 2026-10-02 21:26

import django.core.serializers.json
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_medica', '0040_plan_migracion_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id_change', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('table', models.CharField(db_column='tabla', max_length=40)),
                ('key', models.CharField(db_column='llave', max_length=80)),
                ('action', models.CharField(choices=[('A', 'Alta'), ('M', 'Modificacion'), ('B', 'Baja')], db_column='accion', max_length=1)),
                ('reason', models.CharField(db_column='motivo', max_length=60)),
                ('previous_value', models.JSONField(blank=True, db_column='valor_anterior', encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('new_value', models.JSONField(blank=True, db_column='valor_nuevo', encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('user', models.CharField(db_column='usuario', max_length=40)),
                ('occurred_at', models.DateTimeField(db_column='fecha_hora', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'cns_bitacora_cambios',
                'ordering': ['occurred_at', 'id_change'],
                'indexes': [models.Index(fields=['table', 'key', 'occurred_at'], name='cns_bitacora_registro_idx'), models.Index(fields=['reason', 'occurred_at'], name='cns_bitacora_motivo_idx')],
            },
        ),
    ]
