# Generated by Django 6.0.4 on 2026-10-02 21:38

"""
PACIENTE como tabla propia (documento "Historia Clinica Unificada", 5.1):
uuid estable, datos copiados de SERMED, origen de la CURP, y los dos
identificadores del familiar (pk_num de SERMED y cd_familiar del legado).

pk_num pasa a admitir NULL (familiar del legado sin PK_NUM) y su columna se
renombra de tp_paciente a pk_num, como en el resto de las tablas cns_*.
"""
import uuid

from django.db import migrations, models


def _asignar_uuid(apps, schema_editor):
    Patient = apps.get_model('consulta_medica', 'Patient')
    for patient in Patient.objects.filter(uuid__isnull=True).only('pk').iterator(chunk_size=2000):
        Patient.objects.filter(pk=patient.pk).update(uuid=uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0035_cat_perfil_acceso'),
        ('consulta_medica', '0041_bitacora_cambios'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='patient',
            name='cns_paciente_uniq',
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, db_column='fe_nacimiento', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='curp_source',
            field=models.CharField(blank=True, choices=[('O', 'Oracle (SERMED)'), ('C', 'Capturada en SIRES')], db_column='curp_origen', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(blank=True, db_column='ds_nombre', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='legacy_family_code',
            field=models.IntegerField(blank=True, db_column='cd_familiar', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='maternal_surname',
            field=models.CharField(blank=True, db_column='ds_materno', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='paternal_surname',
            field=models.CharField(blank=True, db_column='ds_paterno', max_length=100, null=True),
        ),
        # uuid en tres pasos: un default callable en un campo unique le daria el
        # MISMO valor a todas las filas existentes. Primero sin unique, despues
        # uno distinto por fila, y al final unique + NOT NULL.
        migrations.AddField(
            model_name='patient',
            name='uuid',
            field=models.UUIDField(db_column='uuid', null=True, editable=False),
        ),
        migrations.RunPython(_asignar_uuid, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='patient',
            name='uuid',
            field=models.UUIDField(db_column='uuid', default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pk_num',
            field=models.IntegerField(blank=True, db_column='pk_num', default=0, null=True),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('pk_num__isnull', False)), fields=('no_exp', 'pk_num'), name='cns_paciente_exp_pknum_uq'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('legacy_family_code__isnull', False)), fields=('legacy_family_code',), name='cns_paciente_cd_familiar_uq'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(condition=models.Q(('pk_num__isnull', False), ('legacy_family_code__isnull', False), _connector='OR'), name='cns_paciente_con_identificador'),
        ),
    ]
