# Generated by Django 6.0.4 on 2026-09-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_modulo_es_sistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='DntFotosCredenciales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empleado', models.IntegerField(db_column='ID_EMPLEADO')),
                ('tipo_foto', models.CharField(blank=True, db_column='TIPO_FOTO', max_length=40, null=True)),
                ('foto', models.BinaryField(blank=True, db_column='FOTO', null=True)),
                ('fecha_toma', models.DateTimeField(auto_now_add=True, db_column='FECHA_TOMA')),
                ('fec_actualizacion', models.DateTimeField(auto_now=True, db_column='FEC_ACTUALIZACION', null=True)),
                ('pk_num', models.IntegerField(blank=True, db_column='PK_NUM', null=True)),
                ('id_clave_foto', models.IntegerField(blank=True, db_column='ID_CLAVE_FOTO', null=True)),
            ],
            options={
                'db_table': 'dnt_fotos_credenciales',
                'managed': False,
            },
        ),
    ]
