# Generated by Django 6.0.4 on 2026-09-28 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_dntfotoscredenciales'),
        ('authentication', '0015_alter_detusuario_paterno'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudArco',
            fields=[
                ('id_solicitud', models.BigAutoField(db_column='id_solicitud', primary_key=True, serialize=False)),
                ('folio', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('acceso', 'Acceso'), ('rectificacion', 'Rectificacion'), ('cancelacion', 'Cancelacion'), ('oposicion', 'Oposicion')], max_length=20)),
                ('estatus', models.CharField(choices=[('recibida', 'Recibida'), ('en_proceso', 'En proceso'), ('procedente', 'Procedente'), ('improcedente', 'Improcedente')], db_index=True, default='recibida', max_length=20)),
                ('no_exp', models.CharField(db_index=True, max_length=20)),
                ('pk_num', models.IntegerField(default=0)),
                ('solicitante_nombre', models.CharField(max_length=255)),
                ('solicitante_relacion', models.CharField(choices=[('titular', 'Titular de los datos'), ('representante', 'Representante legal')], default='titular', max_length=20)),
                ('solicitante_correo', models.CharField(blank=True, max_length=255, null=True)),
                ('solicitante_telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField()),
                ('fecha_recepcion', models.DateField()),
                ('fecha_limite', models.DateField(db_index=True)),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('fch_resolucion', models.DateTimeField(blank=True, null=True)),
                ('fch_alta', models.DateTimeField(auto_now_add=True)),
                ('fch_modf', models.DateTimeField(auto_now=True)),
                ('registrada_por', models.ForeignKey(db_column='registrada_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_arco_registradas', to='authentication.syusuario')),
                ('resuelta_por', models.ForeignKey(blank=True, db_column='resuelta_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_arco_resueltas', to='authentication.syusuario')),
            ],
            options={
                'db_table': 'solicitudes_arco',
                'ordering': ['-fch_alta'],
                'managed': True,
                'indexes': [models.Index(fields=['no_exp', 'pk_num'], name='solicitudes_arco_paciente_idx')],
            },
        ),
    ]
