# Generated by Django 6.0.4 on 2026-09-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_solicitudarco'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudarco',
            name='folio_unidad_transparencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
