# Generated by Django 6.0.4 on 2026-09-29 00:30

from django.db import migrations, models

# SOLICITUD_ARCO.tipo (documento): A acceso, R rectificacion, C cancelacion,
# O oposicion. fe_respuesta = fecha de la resolucion ya registrada.
TIPOS = {"acceso": "A", "rectificacion": "R", "cancelacion": "C", "oposicion": "O"}


def forwards(apps, schema_editor):
    SolicitudArco = apps.get_model("administracion", "SolicitudArco")
    for old, new in TIPOS.items():
        SolicitudArco.objects.filter(tipo=old).update(tipo=new)
    for solicitud in SolicitudArco.objects.exclude(fch_resolucion=None):
        solicitud.fecha_respuesta = solicitud.fch_resolucion.date()
        solicitud.save(update_fields=["fecha_respuesta"])


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_solicitudarco_folio_transparencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudarco',
            name='fecha_respuesta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='solicitudarco',
            name='tipo',
            field=models.CharField(choices=[('A', 'Acceso'), ('R', 'Rectificacion'), ('C', 'Cancelacion'), ('O', 'Oposicion')], max_length=1),
        ),
    ]
