# Generated by Django 6.0.4 on 2026-09-29 00:39

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import TextField
from django.db.models.fields.json import KeyTextTransform
from django.db.models.functions import Cast


def copiar_accesos_previos(apps, schema_editor):
    """Pasa a bitacora_acceso los accesos que ya se habian registrado en
    auditoria_eventos (Fase 3). En la Postgres real `meta` es de tipo json
    (no jsonb): se extrae cada clave como texto con ->> + cast, sin cargar
    la columna JSON como campo (ver repositories/access_log_repository.py)."""
    AuditoriaEvento = apps.get_model("administracion", "AuditoriaEvento")
    BitacoraAcceso = apps.get_model("administracion", "BitacoraAcceso")
    text = lambda key, column="meta": Cast(KeyTextTransform(key, column), TextField())
    rows = (
        AuditoriaEvento.objects.filter(accion__in=["PatientRecordAccessed", "SensitiveDiagnosisRedacted"])
        .annotate(m_no_exp=text("noExp"), m_pk=text("pkNum"), m_section=text("section"),
                  m_endpoint=text("endpoint"), m_count=text("count", "datos_despues"))
        .values("accion", "fch_evento", "ip_origen", "actor_usuario_id", "actor_usuario__usuario",
                "m_no_exp", "m_pk", "m_section", "m_endpoint", "m_count")
        .order_by("id_evento")
    )
    for row in rows.iterator():
        redacted = row["accion"] == "SensitiveDiagnosisRedacted"
        entry = BitacoraAcceso.objects.create(
            no_exp=row["m_no_exp"],
            tp_paciente=int(row["m_pk"]) if (row["m_pk"] or "").lstrip("-").isdigit() else None,
            usuario_id=row["actor_usuario_id"],
            cd_usuario=row["actor_usuario__usuario"],
            recurso=row["m_section"] or ("consultas" if redacted else "expediente"),
            accion="ver",
            ip_origen=row["ip_origen"],
            endpoint=row["m_endpoint"],
            restringidos=int(row["m_count"]) if redacted and (row["m_count"] or "").isdigit() else 0,
        )
        BitacoraAcceso.objects.filter(pk=entry.pk).update(fecha_hora=row["fch_evento"])


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_solicitudarco_fecha_respuesta'),
        ('authentication', '0015_alter_detusuario_paterno'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraAcceso',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('no_exp', models.CharField(blank=True, max_length=20, null=True)),
                ('tp_paciente', models.IntegerField(blank=True, null=True)),
                ('cd_usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('recurso', models.CharField(max_length=40)),
                ('accion', models.CharField(choices=[('ver', 'Ver'), ('imprimir', 'Imprimir'), ('exportar', 'Exportar'), ('modificar', 'Modificar')], max_length=10)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('restringidos', models.PositiveIntegerField(default=0)),
                ('usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authentication.syusuario')),
            ],
            options={
                'db_table': 'bitacora_acceso',
                'ordering': ['-fecha_hora', '-id'],
                'managed': True,
                'indexes': [models.Index(fields=['no_exp', 'tp_paciente'], name='bitacora_acceso_paciente_idx'), models.Index(fields=['accion', 'fecha_hora'], name='bitacora_acceso_accion_idx')],
            },
        ),
        migrations.RunPython(copiar_accesos_previos, migrations.RunPython.noop),
    ]
