"""
Transcripción CONGELADA de `frontend/src/app/navigation/nav-config.ts`
(`NAV_CONFIG` + `NAV_SECONDARY`) a literales Python.

Este archivo NO parsea el `.ts` en runtime — es una copia manual, hecha una
única vez, de la estructura de navegación vigente al momento de crear el
change `menu-modulos`. Si `nav-config.ts` cambia después de este punto,
`nav-config.ts` queda como fallback permanente (ver design) y este seed NO
se re-generа automáticamente; cualquier alta/edición futura del menú se hace
directo en `cat_modulos` (Django admin) o actualizando este archivo a mano.

Cada entrada de `NAV_SEED` es un dict plano (lista, no árbol anidado) con:
  - clave: identificador único, estable, en notación de puntos
           (ej. "administracion.panel.usuarios"). Es la PK lógica del seed.
  - titulo: texto tal cual aparece en `nav-config.ts` (se preserva
            ortografía/acentuación original, incluidas inconsistencias).
  - icono: nombre kebab-case del ícono Lucide usado en el nodo, o None si el
           nodo no define `icon` en el origen. El mapeo string->componente
           vive SOLO en el frontend (`app/navigation/nav-icons.ts`).
  - url: ruta del ítem, o None si el nodo es un contenedor sin navegación
         propia (secciones raíz y grupos como "Panel"/"Catalogos").
  - badge: "Dev" si el nodo usaba `PLACEHOLDER_BADGE` en el origen, si no
           None.
  - orden: posición 0-based dentro de su padre, según el orden de aparición
           en `nav-config.ts`.
  - es_seccion: True solo para las 8 secciones raíz de `NAV_CONFIG`
                (equivalentes a `NavSection`).
  - grupo: "primary" para todo lo proveniente de `NAV_CONFIG`, "secondary"
           para lo proveniente de `NAV_SECONDARY`.
  - parent_clave: `clave` del nodo padre, o None si es raíz. El management
                  command resuelve esta referencia a `id_parent` (FK real).
  - permisos: lista de códigos de `catalogos.Permisos` tomados del array
              `permissions: [...]` del nodo origen. Lista vacía si el nodo
              no restringe por permiso (siempre visible una vez visible su
              padre).


NOTA sobre `CLAVES_SISTEMA` (más abajo): NAV_CONFIG en el frontend tiene 8
secciones raíz (incluye "Urgencias"), pero esa sección NUNCA se transcribió
a este seed -- es un gap preexistente, no introducido acá. Por eso
`CLAVES_SISTEMA` marca las 7 secciones raíz que SÍ existen en `NAV_SEED`
(`es_seccion=True`), no 8. Si "Urgencias" se transcribe en el futuro, sumar
su `clave` acá.
"""

# Claves de módulos "de sistema": protegidos de ocultarse/moverse desde la
# UI de gestión de menús (ver `Modulo.es_sistema`). Lista EXPLÍCITA, no
# derivada de `es_seccion` -- así el admin no puede autobloquearse ocultando
# "Administracion" y perdiendo acceso a la propia pantalla de gestión.
#
# La migración `0005_modulo_es_sistema` aplica esta misma lista como
# literal congelado (las migraciones no deben importar código de la app que
# puede cambiar) sobre datos existentes, una única vez. Este seed la
# reafirma en cada corrida para que sea idempotente y sobreviva un re-seed
# futuro (ver `seed_navigation_menu.py`).
CLAVES_SISTEMA: frozenset[str] = frozenset(
    {
        # 7 secciones raíz existentes en NAV_SEED (es_seccion=True).
        "administracion",
        "clinico",
        "recepcion",
        "farmacia",
        "almacen",
        "servicios",
        "core",
        # Nodos de roles/usuarios bajo Administracion > Panel: sin acceso a
        # "Roles" o "Usuarios" el admin no puede revertir un bloqueo propio.
        "administracion.panel",
        "administracion.panel.roles",
        "administracion.panel.usuarios",
        # Gestion del propio menu: mismo criterio -- si el admin se oculta
        # este nodo pierde la unica pantalla desde la que puede revertirlo.
        "administracion.panel.menus",
    }
)

NAV_SEED = [
    # ── Administracion ──────────────────────────────────────────────────
    {
        "clave": "administracion",
        "titulo": "Administracion",
        "icono": None,
        "url": None,
        "badge": None,
        "orden": 0,
        "es_seccion": True,
        "grupo": "primary",
        "parent_clave": None,
        "permisos": [],
    },
    {
        "clave": "administracion.panel",
        "titulo": "Panel",
        "icono": "shield-user",
        "url": None,
        "badge": None,
        "orden": 0,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion",
        "permisos": [],
    },
    {
        "clave": "administracion.panel.usuarios",
        "titulo": "Usuarios",
        "icono": None,
        "url": "/admin/usuarios",
        "badge": None,
        "orden": 0,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.panel",
        "permisos": ["admin:gestion:usuarios:read"],
    },
    {
        "clave": "administracion.panel.medicos",
        "titulo": "Médicos",
        "icono": None,
        "url": "/admin/medicos",
        "badge": None,
        "orden": 1,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.panel",
        "permisos": ["admin:gestion:medicos:read"],
    },
    {
        "clave": "administracion.panel.expedientes",
        "titulo": "Expedientes",
        "icono": None,
        "url": "/admin/expedientes",
        "badge": "Dev",
        "orden": 2,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.panel",
        "permisos": ["admin:gestion:expedientes:read"],
    },
    {
        "clave": "administracion.panel.roles",
        "titulo": "Roles",
        "icono": None,
        "url": "/admin/roles",
        "badge": None,
        "orden": 3,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.panel",
        "permisos": ["admin:gestion:roles:read"],
    },
    {
        "clave": "administracion.panel.conexiones",
        "titulo": "Conexiones",
        "icono": None,
        "url": "/admin/conexiones",
        "badge": None,
        "orden": 4,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.panel",
        "permisos": ["admin:usuarios:sesiones:read"],
    },
    {
        "clave": "administracion.catalogos",
        "titulo": "Catalogos",
        "icono": "book-open",
        "url": None,
        "badge": None,
        "orden": 1,
        "es_seccion": True,
        "grupo": "primary",
        "parent_clave": "administracion",
        "permisos": [],
    },
    {
        "clave": "administracion.catalogos.areas",
        "titulo": "Areas",
        "icono": None,
        "url": "/admin/catalogos/areas",
        "badge": None,
        "orden": 0,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:areas:read"],
    },
    {
        "clave": "administracion.catalogos.centros_atencion",
        "titulo": "Centros de atencion",
        "icono": None,
        "url": "/admin/catalogos/centros-atencion",
        "badge": None,
        "orden": 7,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:centros_atencion:read"],
    },
    {
        "clave": "administracion.catalogos.autorizadores",
        "titulo": "Autorizadores",
        "icono": None,
        "url": "/admin/catalogos/autorizadores",
        "badge": None,
        "orden": 3,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:autorizadores:read"],
    },
    {
        "clave": "administracion.catalogos.bajas",
        "titulo": "Bajas",
        "icono": None,
        "url": "/admin/catalogos/bajas",
        "badge": None,
        "orden": 4,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:bajas:read"],
    },
    {
        "clave": "administracion.catalogos.calidad_laboral",
        "titulo": "Calidad laboral",
        "icono": None,
        "url": "/admin/catalogos/calidad-laboral",
        "badge": None,
        "orden": 5,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:calidad_laboral:read"],
    },
    {
        "clave": "administracion.catalogos.edo_civil",
        "titulo": "Estado civil",
        "icono": None,
        "url": "/admin/catalogos/edo-civil",
        "badge": None,
        "orden": 12,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:edo_civil:read"],
    },
    {
        "clave": "administracion.catalogos.sucursales",
        "titulo": "Sucursales",
        "icono": None,
        "url": "/admin/catalogos/sucursales",
        "badge": None,
        "orden": 21,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:sucursales:read"],
    },
    {
        "clave": "administracion.catalogos.enfermedades",
        "titulo": "Enfermedades",
        "icono": None,
        "url": "/admin/catalogos/enfermedades",
        "badge": None,
        "orden": 8,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:enfermedades:read"],
    },
    {
        "clave": "administracion.catalogos.escolaridad",
        "titulo": "Escolaridad",
        "icono": None,
        "url": "/admin/catalogos/escolaridad",
        "badge": None,
        "orden": 9,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:escolaridad:read"],
    },
    {
        "clave": "administracion.catalogos.tipo_personal",
        "titulo": "Tipos de personal",
        "icono": None,
        "url": "/admin/catalogos/tipo-personal",
        "badge": None,
        "orden": 25,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:tipo_personal:read"],
    },
    {
        "clave": "administracion.catalogos.escuelas",
        "titulo": "Escuelas",
        "icono": None,
        "url": "/admin/catalogos/escuelas",
        "badge": None,
        "orden": 10,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:escuelas:read"],
    },
    {
        "clave": "administracion.catalogos.especialidades",
        "titulo": "Especialidades",
        "icono": None,
        "url": "/admin/catalogos/especialidades",
        "badge": None,
        "orden": 11,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:especialidades:read"],
    },
    {
        "clave": "administracion.catalogos.tipo_consulta",
        "titulo": "Tipos de consulta",
        "icono": None,
        "url": "/admin/catalogos/tipos-consulta",
        "badge": None,
        "orden": 12,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:tipo_consulta:read"],
    },
    {
        "clave": "administracion.catalogos.estudios_medicos",
        "titulo": "Estudios medicos",
        "icono": None,
        "url": "/admin/catalogos/estudios-medicos",
        "badge": None,
        "orden": 13,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:estudios_med:read"],
    },
    {
        "clave": "administracion.catalogos.grupos_medicamentos",
        "titulo": "Grupos de medicamentos",
        "icono": None,
        "url": "/admin/catalogos/grupos-medicamentos",
        "badge": None,
        "orden": 14,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:grupos_medicamentos:read"],
    },
    {
        "clave": "administracion.catalogos.ocupaciones",
        "titulo": "Ocupaciones",
        "icono": None,
        "url": "/admin/catalogos/ocupaciones",
        "badge": None,
        "orden": 17,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:ocupaciones:read"],
    },
    {
        "clave": "administracion.catalogos.origen_consulta",
        "titulo": "Origen de consulta",
        "icono": None,
        "url": "/admin/catalogos/origen-consulta",
        "badge": None,
        "orden": 18,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:origen_cons:read"],
    },
    {
        "clave": "administracion.catalogos.parentescos",
        "titulo": "Parentescos",
        "icono": None,
        "url": "/admin/catalogos/parentescos",
        "badge": None,
        "orden": 19,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:parentescos:read"],
    },
    {
        "clave": "administracion.catalogos.pases",
        "titulo": "Pases",
        "icono": None,
        "url": "/admin/catalogos/pases",
        "badge": None,
        "orden": 20,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:pases:read"],
    },
    {
        "clave": "administracion.catalogos.tipos_areas",
        "titulo": "Tipos de areas",
        "icono": None,
        "url": "/admin/catalogos/tipos-areas",
        "badge": None,
        "orden": 22,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:tipos_areas:read"],
    },
    {
        "clave": "administracion.catalogos.tipos_autorizacion",
        "titulo": "Tipos de autorizacion",
        "icono": None,
        "url": "/admin/catalogos/tipos-autorizacion",
        "badge": None,
        "orden": 23,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:tp_autorizacion:read"],
    },
    {
        "clave": "administracion.catalogos.tipos_citas",
        "titulo": "Tipos de citas",
        "icono": None,
        "url": "/admin/catalogos/tipos-citas",
        "badge": None,
        "orden": 24,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:tipo_citas:read"],
    },
    {
        "clave": "administracion.catalogos.licencias",
        "titulo": "Licencias",
        "icono": None,
        "url": "/admin/catalogos/licencias",
        "badge": None,
        "orden": 15,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:licencias:read"],
    },
    {
        "clave": "administracion.catalogos.tipos_sanguineo",
        "titulo": "Tipos sanguineos",
        "icono": None,
        "url": "/admin/catalogos/tipos-sanguineo",
        "badge": None,
        "orden": 26,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:tipos_sanguineo:read"],
    },
    {
        "clave": "administracion.catalogos.turnos",
        "titulo": "Turnos",
        "icono": None,
        "url": "/admin/catalogos/turnos",
        "badge": None,
        "orden": 27,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:turnos:read"],
    },
    {
        "clave": "administracion.catalogos.vacunas",
        "titulo": "Vacunas",
        "icono": None,
        "url": "/admin/catalogos/vacunas",
        "badge": None,
        "orden": 28,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:vacunas:read"],
    },
    {
        "clave": "administracion.catalogos.estudios",
        "titulo": "Estudios",
        "icono": None,
        "url": "/admin/catalogos/estudios",
        "badge": None,
        "orden": 29,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:estudios:read"],
    },
    {
        "clave": "administracion.catalogos.areas_clinicas",
        "titulo": "Áreas clínicas",
        "icono": None,
        "url": "/admin/catalogos/areas-clinicas",
        "badge": None,
        "orden": 1,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:areas_clinicas:read"],
    },
    {
        "clave": "administracion.catalogos.centro_area_clinica",
        "titulo": "Áreas clínicas por centro",
        "icono": None,
        "url": "/admin/catalogos/centro-area-clinica",
        "badge": None,
        "orden": 2,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:centro_area_clinica:read"],
    },
    {
        "clave": "administracion.catalogos.cies",
        "titulo": "Catálogo CIES",
        "icono": None,
        "url": "/admin/catalogos/cies",
        "badge": None,
        "orden": 6,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:cies:upload"],
    },
    {
        "clave": "administracion.catalogos.discapacidades",
        "titulo": "Discapacidades",
        "icono": None,
        "url": "/admin/catalogos/discapacidades",
        "badge": None,
        "orden": 30,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:discapacidades:read"],
    },
    {
        "clave": "administracion.catalogos.religion",
        "titulo": "Religiones",
        "icono": None,
        "url": "/admin/catalogos/religiones",
        "badge": None,
        "orden": 31,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:religion:read"],
    },
    {
        "clave": "administracion.catalogos.tipo_residencia",
        "titulo": "Tipos de residencia",
        "icono": None,
        "url": "/admin/catalogos/tipos-residencia",
        "badge": None,
        "orden": 32,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:catalogos:tipo_residencia:read"],
    },
    {
        # Agregado 2026-09-13: "Reportes y Analitica Operativa" existe en
        # nav-config.ts (linea ~271) desde antes como item plano con
        # PLACEHOLDER_BADGE, pero nunca se transcribio a este seed -- por
        # eso el sidebar nunca mostraba nada aqui. Se transcribe ahora como
        # seccion con hijos reales (los placeholders en nav-config.ts/router
        # se reemplazan por las paginas construidas).
        "clave": "administracion.reportes",
        "titulo": "Reportes y Analitica Operativa",
        "icono": "file-text",
        "url": None,
        "badge": None,
        "orden": 2,
        "es_seccion": True,
        "grupo": "primary",
        "parent_clave": "administracion",
        "permisos": [],
    },
    {
        "clave": "administracion.reportes.consultas_diario",
        "titulo": "Informe Diario de Consulta Médica",
        "icono": None,
        "url": "/admin/reportes/consultas-diario",
        "badge": None,
        "orden": 0,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.reportes",
        "permisos": ["clinico:reportes:read"],
    },
    {
        "clave": "administracion.reportes.pases",
        "titulo": "Informe de Pases",
        "icono": None,
        "url": "/admin/reportes/pases",
        "badge": None,
        "orden": 1,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.reportes",
        "permisos": ["clinico:pases:read"],
    },
    {
        "clave": "administracion.panel.menus",
        "titulo": "Menús y Submenús",
        "icono": None,
        "url": "/admin/menus",
        "badge": None,
        "orden": 29,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "administracion.catalogos",
        "permisos": ["admin:gestion:modulos:read"],
    },
    # ── Clinico ──────────────────────────────────────────────────────────
    {
        "clave": "clinico",
        "titulo": "Clinico",
        "icono": None,
        "url": None,
        "badge": None,
        "orden": 2,
        "es_seccion": True,
        "grupo": "primary",
        "parent_clave": None,
        "permisos": [],
    },
    {
        "clave": "clinico.consultas",
        "titulo": "Consultas",
        "icono": "stethoscope",
        "url": None,
        "badge": None,
        "orden": 0,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "clinico",
        "permisos": [],
    },
    {
        "clave": "clinico.consultas.panel",
        "titulo": "Panel",
        "icono": None,
        "url": "/clinico/consultas",
        "badge": None,
        "orden": 0,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "clinico.consultas",
        "permisos": ["clinico:consultas:read"],
    },
    {
        "clave": "clinico.consultas.bandeja",
        "titulo": "Bandeja",
        "icono": None,
        "url": "/clinico/consultas/doctor",
        "badge": None,
        "orden": 4,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "clinico.consultas",
        "permisos": ["clinico:consultas:read"],
    },
    {
        "clave": "clinico.somatometria",
        "titulo": "Somatometria",
        "icono": "activity",
        "url": "/clinico/somatometria",
        "badge": None,
        "orden": 2,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "clinico",
        "permisos": ["clinico:somatometria:read"],
    },
    # ── Recepcion ────────────────────────────────────────────────────────
    {
        "clave": "recepcion",
        "titulo": "Recepcion",
        "icono": None,
        "url": None,
        "badge": None,
        "orden": 3,
        "es_seccion": True,
        "grupo": "primary",
        "parent_clave": None,
        "permisos": [],
    },
    {
        "clave": "recepcion.agenda",
        "titulo": "Citas y check-in",
        "icono": "calendar-clock",
        "url": "/recepcion/agenda",
        "badge": None,
        "orden": 0,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "recepcion",
        "permisos": [
            "recepcion:fichas:medicina_general:create",
            "recepcion:fichas:especialidad:create",
            "recepcion:fichas:urgencias:create",
            "clinico:consultas:read",
            "clinico:somatometria:read",
        ],
    },
    {
        "clave": "recepcion.fichas",
        "titulo": "Archivo de fichas",
        "icono": "archive",
        "url": "/recepcion/fichas",
        "badge": None,
        "orden": 1,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "recepcion",
        "permisos": [
            "recepcion:fichas:medicina_general:create",
            "recepcion:fichas:especialidad:create",
            "recepcion:fichas:urgencias:create",
            "clinico:consultas:read",
            "clinico:somatometria:read",
        ],
    },
    {
        "clave": "recepcion.turnos",
        "titulo": "Turnos de fichas",
        "icono": "clock",
        "url": "/recepcion/turnos",
        "badge": None,
        "orden": 2,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "recepcion",
        "permisos": [
            "recepcion:fichas:medicina_general:create",
            "recepcion:fichas:especialidad:create",
            "recepcion:fichas:urgencias:create",
        ],
    },
    # ── Farmacia ─────────────────────────────────────────────────────────
    {
        "clave": "farmacia",
        "titulo": "Farmacia",
        "icono": None,
        "url": None,
        "badge": None,
        "orden": 4,
        "es_seccion": True,
        "grupo": "primary",
        "parent_clave": None,
        "permisos": [],
    },
    {
        "clave": "farmacia.vacunas",
        "titulo": "Inventario de vacunas",
        "icono": "pill",
        "url": "/farmacia/vacunas",
        "badge": None,
        "orden": 0,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "farmacia",
        "permisos": ["farmacia:vacunas:read"],
    },
    # ── Almacén ──────────────────────────────────────────────────────────
    {
        "clave": "almacen",
        "titulo": "Almacén",
        "icono": None,
        "url": None,
        "badge": None,
        "orden": 5,
        "es_seccion": True,
        "grupo": "primary",
        "parent_clave": None,
        "permisos": ["almacen:inventario:read"],
    },
    {
        "clave": "almacen.dashboard",
        "titulo": "Dashboard",
        "icono": "warehouse",
        "url": "/almacen/dashboard",
        "badge": None,
        "orden": 0,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "almacen",
        "permisos": [],
    },
    {
        "clave": "almacen.catalogos",
        "titulo": "Catálogos",
        "icono": "book-open",
        "url": None,
        "badge": None,
        "orden": 1,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "almacen",
        "permisos": [],
    },
    {
        "clave": "almacen.catalogos.insumos",
        "titulo": "Insumos",
        "icono": None,
        "url": "/almacen/insumos",
        "badge": None,
        "orden": 0,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "almacen.catalogos",
        "permisos": [],
    },
    {
        "clave": "almacen.catalogos.categorias",
        "titulo": "Categorías",
        "icono": None,
        "url": "/almacen/categorias",
        "badge": None,
        "orden": 1,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "almacen.catalogos",
        "permisos": [],
    },
    {
        "clave": "almacen.catalogos.proveedores",
        "titulo": "Proveedores",
        "icono": None,
        "url": "/almacen/proveedores",
        "badge": None,
        "orden": 2,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "almacen.catalogos",
        "permisos": [],
    },
    {
        "clave": "almacen.catalogos.unidades_medida",
        "titulo": "Unidades de medida",
        "icono": None,
        "url": "/almacen/unidades-medida",
        "badge": None,
        "orden": 3,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "almacen.catalogos",
        "permisos": [],
    },
    {
        "clave": "almacen.catalogos.almacenes",
        "titulo": "Almacenes",
        "icono": None,
        "url": "/almacen/almacenes",
        "badge": None,
        "orden": 4,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "almacen.catalogos",
        "permisos": [],
    },
    {
        "clave": "almacen.movimientos",
        "titulo": "Movimientos",
        "icono": "package",
        "url": None,
        "badge": None,
        "orden": 2,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "almacen",
        "permisos": [],
    },
    {
        "clave": "almacen.movimientos.entradas",
        "titulo": "Entradas",
        "icono": None,
        "url": "/almacen/entradas",
        "badge": None,
        "orden": 0,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "almacen.movimientos",
        "permisos": [],
    },
    {
        "clave": "almacen.movimientos.salidas",
        "titulo": "Salidas / Mermas",
        "icono": None,
        "url": "/almacen/salidas",
        "badge": None,
        "orden": 1,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "almacen.movimientos",
        "permisos": [],
    },
    {
        "clave": "almacen.movimientos.consumos",
        "titulo": "Consumos por consulta",
        "icono": None,
        "url": "/almacen/consumos",
        "badge": None,
        "orden": 2,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "almacen.movimientos",
        "permisos": [],
    },
    {
        "clave": "almacen.inventario",
        "titulo": "Inventario",
        "icono": "clipboard-list",
        "url": None,
        "badge": None,
        "orden": 3,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "almacen",
        "permisos": [],
    },
    {
        "clave": "almacen.inventario.existencias",
        "titulo": "Existencias",
        "icono": None,
        "url": "/almacen/existencias",
        "badge": None,
        "orden": 0,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "almacen.inventario",
        "permisos": [],
    },
    {
        "clave": "almacen.inventario.kardex",
        "titulo": "Kardex",
        "icono": None,
        "url": "/almacen/kardex",
        "badge": None,
        "orden": 1,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "almacen.inventario",
        "permisos": [],
    },
    {
        "clave": "almacen.inventario.conteos",
        "titulo": "Conteos físicos",
        "icono": None,
        "url": "/almacen/conteos",
        "badge": None,
        "orden": 2,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "almacen.inventario",
        "permisos": [],
    },
    # ── Servicios ────────────────────────────────────────────────────────
    {
        "clave": "servicios",
        "titulo": "Servicios",
        "icono": None,
        "url": None,
        "badge": None,
        "orden": 6,
        "es_seccion": True,
        "grupo": "primary",
        "parent_clave": None,
        "permisos": [],
    },
    {
        "clave": "servicios.contratos_oxigeno",
        "titulo": "Contratos de oxígeno",
        "icono": "scroll-text",
        "url": "/servicios/contratos-oxigeno",
        "badge": None,
        "orden": 0,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "servicios",
        "permisos": ["servicios:contratos_oxigeno:read"],
    },
    # ── Core ─────────────────────────────────────────────────────────────
    {
        "clave": "core",
        "titulo": "Core",
        "icono": None,
        "url": None,
        "badge": None,
        "orden": 7,
        "es_seccion": True,
        "grupo": "primary",
        "parent_clave": None,
        "permisos": [],
    },
    {
        "clave": "core.dashboard",
        "titulo": "Dashboard",
        "icono": "layout-dashboard",
        "url": "/dashboard",
        "badge": None,
        "orden": 0,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "core",
        "permisos": [],
    },
    # ── NAV_SECONDARY (acciones globales, sin sección padre) ────────────
    # ── Comunicados (change `anuncios-portal-citas`) ────────────────────
    {
        "clave": "comunicados",
        "titulo": "Comunicados",
        "icono": None,
        "url": None,
        "badge": None,
        "orden": 8,
        "es_seccion": True,
        "grupo": "primary",
        "parent_clave": None,
        "permisos": [],
    },
    {
        "clave": "comunicados.anuncios",
        "titulo": "Anuncios",
        "icono": "bell",
        "url": "/comunicados/anuncios",
        "badge": None,
        "orden": 0,
        "es_seccion": False,
        "grupo": "primary",
        "parent_clave": "comunicados",
        "permisos": ["comunicados:anuncios:read"],
    },
    {
        "clave": "secondary.soporte",
        "titulo": "Soporte",
        "icono": "shield",
        "url": "/soporte",
        "badge": None,
        "orden": 0,
        "es_seccion": False,
        "grupo": "secondary",
        "parent_clave": None,
        "permisos": [],
    },
    {
        "clave": "secondary.feedback",
        "titulo": "Enviar Feedback",
        "icono": "book-open",
        "url": "/feedback",
        "badge": None,
        "orden": 1,
        "es_seccion": False,
        "grupo": "secondary",
        "parent_clave": None,
        "permisos": [],
    },
]
