from django.urls import path

from apps.consulta_medica.views import (
    DailyConsultationReportView,
    MedicalLeaveReportView,
    PatientAllergiesView,
    PatientAllergyDetailView,
    PatientClinicalHistoryView,
    PatientConsultationsHistoryView,
    PatientLegacyConsultationsHistoryView,
    PatientMedicalLeavesHistoryView,
    PatientOdontogramToothView,
    PatientOdontogramView,
    PatientProfileView,
    PatientStomatologyHistoryView,
    PatientStudyResultsHistoryView,
    PrescriptionAuthorizationDecisionView,
    PrescriptionAuthorizationRejectView,
    PrescriptionAuthorizationsHistoryView,
    PrescriptionAuthorizationsPendingView,
    PrescriptionDispensationsPendingView,
    PrescriptionDispensationView,
    PrescriptionDispenseView,
    VisitCieSearchView,
    VisitConsultationAddendumView,
    VisitConsultationCloseView,
    VisitConsultationStartView,
    VisitDiagnosisSaveView,
    VisitMedicalLeaveCreateView,
    VisitPrescriptionItemCancelView,
    VisitPrescriptionItemsView,
    VisitPrescriptionsSaveView,
    VisitSecondaryDiagnosesView,
    VisitSecondaryDiagnosisCancelView,
    VisitStudyResultCreateView,
)
from apps.consulta_medica.views_unified_history import (
    ClinicalCatalogsView,
    DentalTreatmentCollectionView,
    DentalTreatmentDetailView,
    FamilyHistoryCollectionView,
    FamilyHistoryDetailView,
    HabitCollectionView,
    HabitDetailView,
    PatientAllergyStatusView,
    PatientHistoricalNotesView,
    PatientOdontogramVersionsView,
    PersonalHistoryCollectionView,
    PersonalHistoryDetailView,
    SurgicalHistoryCollectionView,
    SurgicalHistoryDetailView,
    VisitPhysicalExamView,
)

# Historia clinica unificada: registros permanentes (coleccion + detalle).
_PATIENT_RECORD_ROUTES = (
    ("personal-history", PersonalHistoryCollectionView, PersonalHistoryDetailView),
    ("family-history", FamilyHistoryCollectionView, FamilyHistoryDetailView),
    ("surgical-history", SurgicalHistoryCollectionView, SurgicalHistoryDetailView),
    ("habits", HabitCollectionView, HabitDetailView),
    ("dental-treatments", DentalTreatmentCollectionView, DentalTreatmentDetailView),
)


urlpatterns = [
    path(
        "visits/cies/search",
        VisitCieSearchView.as_view(),
        name="visit-cies-search",
    ),
    path(
        "patients/<str:no_exp>/clinical-history",
        PatientClinicalHistoryView.as_view(),
        name="patient-clinical-history",
    ),
    path(
        "patients/<str:no_exp>/profile",
        PatientProfileView.as_view(),
        name="patient-profile",
    ),
    path(
        "patients/<str:no_exp>/stomatology-history",
        PatientStomatologyHistoryView.as_view(),
        name="patient-stomatology-history",
    ),
    path(
        "patients/<str:no_exp>/allergies",
        PatientAllergiesView.as_view(),
        name="patient-allergies",
    ),
    path(
        "patients/<str:no_exp>/allergies/<int:allergy_id>",
        PatientAllergyDetailView.as_view(),
        name="patient-allergy-detail",
    ),
    path(
        "patients/<str:no_exp>/allergies/<int:allergy_id>/status",
        PatientAllergyStatusView.as_view(),
        name="patient-allergy-status",
    ),
    path(
        "patients/<str:no_exp>/historical-notes",
        PatientHistoricalNotesView.as_view(),
        name="patient-historical-notes",
    ),
    path("clinical-catalogs", ClinicalCatalogsView.as_view(), name="clinical-catalogs"),
    path(
        "visits/<int:visit_id>/consultation/physical-exam",
        VisitPhysicalExamView.as_view(),
        name="visit-physical-exam",
    ),
    *[
        route
        for slug, collection_view, detail_view in _PATIENT_RECORD_ROUTES
        for route in (
            path(f"patients/<str:no_exp>/{slug}", collection_view.as_view(), name=f"patient-{slug}"),
            path(
                f"patients/<str:no_exp>/{slug}/<int:record_id>",
                detail_view.as_view(),
                name=f"patient-{slug}-detail",
            ),
        )
    ],
    path(
        "patients/<str:no_exp>/odontogram",
        PatientOdontogramView.as_view(),
        name="patient-odontogram",
    ),
    # ANTES que odontogram/<tooth_fdi>: "versions" calzaria como pieza.
    path(
        "patients/<str:no_exp>/odontogram/versions",
        PatientOdontogramVersionsView.as_view(),
        name="patient-odontogram-versions",
    ),
    path(
        "patients/<str:no_exp>/odontogram/<str:tooth_fdi>",
        PatientOdontogramToothView.as_view(),
        name="patient-odontogram-tooth",
    ),
    path(
        "patients/<str:no_exp>/consultations",
        PatientConsultationsHistoryView.as_view(),
        name="patient-consultations-history",
    ),
    path(
        "patients/<str:no_exp>/legacy-consultations",
        PatientLegacyConsultationsHistoryView.as_view(),
        name="patient-legacy-consultations-history",
    ),
    path(
        "visits/<int:visit_id>/medical-leave",
        VisitMedicalLeaveCreateView.as_view(),
        name="visit-medical-leave-create",
    ),
    path(
        "patients/<str:no_exp>/medical-leaves",
        PatientMedicalLeavesHistoryView.as_view(),
        name="patient-medical-leaves-history",
    ),
    path(
        "visits/<int:visit_id>/study-results",
        VisitStudyResultCreateView.as_view(),
        name="visit-study-result-create",
    ),
    path(
        "patients/<str:no_exp>/study-results",
        PatientStudyResultsHistoryView.as_view(),
        name="patient-study-results-history",
    ),
    path(
        "visits/<int:visit_id>/diagnosis",
        VisitDiagnosisSaveView.as_view(),
        name="visit-diagnosis-save",
    ),
    path(
        "visits/<int:visit_id>/diagnoses",
        VisitSecondaryDiagnosesView.as_view(),
        name="visit-secondary-diagnoses",
    ),
    path(
        "visits/<int:visit_id>/diagnoses/<int:diagnosis_id>/cancel",
        VisitSecondaryDiagnosisCancelView.as_view(),
        name="visit-secondary-diagnosis-cancel",
    ),
    path(
        "visits/<int:visit_id>/prescriptions",
        VisitPrescriptionsSaveView.as_view(),
        name="visit-prescriptions-save",
    ),
    path(
        "visits/<int:visit_id>/prescription-items",
        VisitPrescriptionItemsView.as_view(),
        name="visit-prescription-items",
    ),
    path(
        "visits/<int:visit_id>/prescription-items/<int:item_id>/cancel",
        VisitPrescriptionItemCancelView.as_view(),
        name="visit-prescription-item-cancel",
    ),
    path(
        "prescriptions/authorizations/pending",
        PrescriptionAuthorizationsPendingView.as_view(),
        name="prescription-authorizations-pending",
    ),
    path(
        "prescriptions/authorizations",
        PrescriptionAuthorizationsHistoryView.as_view(),
        name="prescription-authorizations-history",
    ),
    path(
        "prescriptions/authorizations/<int:authorization_id>/authorize",
        PrescriptionAuthorizationDecisionView.as_view(),
        name="prescription-authorization-authorize",
    ),
    path(
        "prescriptions/authorizations/<int:authorization_id>/reject",
        PrescriptionAuthorizationRejectView.as_view(),
        name="prescription-authorization-reject",
    ),
    path(
        "prescriptions/dispensations/pending",
        PrescriptionDispensationsPendingView.as_view(),
        name="prescription-dispensations-pending",
    ),
    path(
        "prescriptions/<int:prescription_id>/dispensation",
        PrescriptionDispensationView.as_view(),
        name="prescription-dispensation",
    ),
    path(
        "prescriptions/<int:prescription_id>/dispense",
        PrescriptionDispenseView.as_view(),
        name="prescription-dispense",
    ),
    path(
        "visits/<int:visit_id>/consultation/start",
        VisitConsultationStartView.as_view(),
        name="visit-consultation-start",
    ),
    path(
        "visits/<int:visit_id>/consultation/close",
        VisitConsultationCloseView.as_view(),
        name="visit-consultation-close",
    ),
    path(
        "visits/<int:visit_id>/consultation/addenda",
        VisitConsultationAddendumView.as_view(),
        name="visit-consultation-addenda",
    ),
    path(
        "visits/<int:visit_id>/close",
        VisitConsultationCloseView.as_view(),
        name="visit-close",
    ),
    path(
        "reportes/consultas/diario",
        DailyConsultationReportView.as_view(),
        name="reportes-consultas-diario",
    ),
    path(
        "reportes/incapacidades",
        MedicalLeaveReportView.as_view(),
        name="reportes-incapacidades",
    ),
]
