# Generated by Django 6.0.4 on 2026-09-14 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0027_catclasificacioncirugia_catdestinoambulancia_and_more'),
        ('medicos', '0009_add_nombre_display_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgerySchedule',
            fields=[
                ('id', models.BigAutoField(db_column='id_cirugia', primary_key=True, serialize=False)),
                ('folio', models.CharField(db_column='folio', max_length=32, unique=True)),
                ('legacy_folio', models.CharField(blank=True, db_column='folio_legado', max_length=20, null=True)),
                ('no_exp', models.CharField(db_column='no_exp', db_index=True, max_length=20)),
                ('pk_num', models.IntegerField(db_column='pk_num', default=0)),
                ('origin_clinic_id', models.CharField(blank=True, db_column='cd_clinica_origen', max_length=10, null=True)),
                ('scheduled_date', models.DateField(db_column='fecha_cirugia')),
                ('scheduled_time', models.TimeField(db_column='hora_cirugia')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, db_column='duracion_minutos', null=True)),
                ('contact_phone', models.CharField(blank=True, db_column='telefono_contacto', max_length=20, null=True)),
                ('description', models.TextField(blank=True, db_column='descripcion', null=True)),
                ('diagnosis_text', models.TextField(blank=True, db_column='diagnostico_texto', null=True)),
                ('requirements', models.TextField(blank=True, db_column='requerimientos', null=True)),
                ('status', models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada')], db_column='estatus', default='activa', max_length=20)),
                ('performed_status', models.CharField(choices=[('pendiente', 'Pendiente'), ('realizada', 'Realizada'), ('no_realizada', 'No realizada')], db_column='estatus_realizacion', default='pendiente', max_length=20)),
                ('is_active', models.BooleanField(db_column='est_activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='fch_modf')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='fch_baja', null=True)),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('updated_by_id', models.BigIntegerField(blank=True, db_column='usr_modf', null=True)),
                ('deleted_by_id', models.BigIntegerField(blank=True, db_column='usr_baja', null=True)),
                ('classification', models.ForeignKey(db_column='id_clasificacion', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.catclasificacioncirugia')),
                ('surgeon', models.ForeignKey(db_column='id_medico', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medicos.catmedico')),
                ('surgery_type', models.ForeignKey(db_column='id_tipo_cirugia', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.cattipocirugia')),
            ],
            options={
                'db_table': 'cir_surgery',
            },
        ),
        migrations.CreateModel(
            name='SurgeryDiagnosis',
            fields=[
                ('id', models.BigAutoField(db_column='id_cirugia_diagnostico', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('cie', models.ForeignKey(db_column='cd_cie', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.catcies')),
                ('surgery', models.ForeignKey(db_column='id_cirugia', on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='cirugias.surgeryschedule')),
            ],
            options={
                'db_table': 'cir_surgery_diagnosis',
            },
        ),
        migrations.CreateModel(
            name='SurgeryCancellation',
            fields=[
                ('id', models.BigAutoField(db_column='id_cirugia_cancelacion', primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, db_column='notas', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fch_alta')),
                ('created_by_id', models.BigIntegerField(blank=True, db_column='usr_alta', null=True)),
                ('reason', models.ForeignKey(db_column='id_motivo', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.catmotivocancelacioncirugia')),
                ('surgery', models.ForeignKey(db_column='id_cirugia', on_delete=django.db.models.deletion.PROTECT, related_name='cancellations', to='cirugias.surgeryschedule')),
            ],
            options={
                'db_table': 'cir_surgery_cancellation',
            },
        ),
        migrations.AddIndex(
            model_name='surgeryschedule',
            index=models.Index(fields=['no_exp', 'pk_num'], name='cir_surgery_patient_idx'),
        ),
        migrations.AddIndex(
            model_name='surgeryschedule',
            index=models.Index(fields=['scheduled_date'], name='cir_surgery_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='surgeryschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'activa')), fields=('surgeon', 'scheduled_date', 'scheduled_time'), name='cir_surgery_no_doble_agenda_medico'),
        ),
        migrations.AddConstraint(
            model_name='surgerydiagnosis',
            constraint=models.UniqueConstraint(fields=('surgery', 'cie'), name='cir_surgery_diagnosis_uniq'),
        ),
    ]
